import { KfTarcRolesInterface as Kf } from './kftarc-roles.interface';

export namespace KfRolesUtilMockData {
    const midTierCommercialBanking = 'Mid-tier / Commercial Banking';
    const accountManagerCommercialBanking = 'Account Manager Commercial Banking';
    const administration = 'Administration / Support / Service';
    const clerical = 'Clerical Services';

    export const queryParams = {
        searchString: '',
        sortColumn: '',
        sortBy: '',
        filterBy: '',
        filterValues: '',
        pageIndex: 1,
        pageSize: 20,
        loggedInUserClientId: 23139,
        userId: 23139,
        locale: 'en',
    };

    export const mockDbData = [
        {
            ClientJobId: 92624,
            ParentClientJobID: 92623,
            JobRoleTypeID: 'EGA01',
            JobName: '02.25.2021 CL daily smoke edit',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 14,
            HayReferenceLevel: 14,
            JobFamilyID: 'EG',
            JobFamilyName: 'Engineering',
            JobSubFamilyID: 'EGA',
            JobSubFamilyName: 'General Engineers',
            LevelType: Kf.LevelType.CUSTOM,
            ProfileType: 4,
            ClientId: '12024',
            ShortProfile: 'A3',
            HayPoints: 301,
            JELineScore: 'D+ I 2  175  D 3 29  50  D- N IV+  76      301',
            TotalRoleNumber: 0,
            TotalResultRecords: 2,
            TotalShowRecords: 2,
        },
        {
            ClientJobId: 92625,
            ParentClientJobID: 55916,
            JobRoleTypeID: 'HEA01',
            JobName: '02.25.2021 CL daily smoke loc test job profiles',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 14,
            HayReferenceLevel: 14,
            JobFamilyID: 'HE',
            JobFamilyName: 'Health and Environment',
            JobSubFamilyID: 'HEA',
            JobSubFamilyName: 'Environmental Health',
            LevelType: Kf.LevelType.CUSTOM,
            ProfileType: 4,
            ClientId: '12024',
            ShortProfile: 'A1',
            HayPoints: 298,
            JELineScore: 'E- I 2  175  D+ 3 33  57  D- N IV  66      298',
            TotalRoleNumber: 0,
            TotalResultRecords: 2,
            TotalShowRecords: 2,
        },
    ];

    export const expectedJson = {
        roles: [
            {
                title: '02.25.2021 CL daily smoke edit',
                jobFamily: 'EG',
                jobSubFamily: 'EGA',
                jobRoleTypeId: 'EGA01',
                familyName: 'Engineering',
                subFamilyName: 'General Engineers',
                profileType: Kf.LevelType.CUSTOM,
                id: '92624',
                grade: {
                    standardHayGrade: '14',
                },
                expandable: false,
                shortProfile: 'A3',
                haypoints: {
                    totalPoints: 301,
                    jescores: [
                        {
                            id: 1,
                            jeScoreType: 'KNOW_HOW',
                            rationaleDescription: '',
                            points: '175',
                            options: [
                                {
                                    id: 1,
                                    code: 'D+',
                                    type: 'PRACTICAL_TECHNICAL_KNOWLEDGE',
                                },
                                {
                                    id: 2,
                                    code: 'I',
                                    type: 'MANAGERIAL_KNOWLEDGE',
                                },
                                {
                                    id: 3,
                                    code: '2',
                                    type: 'COMMUNICATION_INFLUENCING_SKILL',
                                },
                            ],
                        },
                        {
                            id: 2,
                            jeScoreType: 'PROBLEM_SOLVING',
                            rationaleDescription: '',
                            points: '50',
                            options: [
                                {
                                    id: 1,
                                    code: 'D',
                                    type: 'FREEDOM_THINK',
                                },
                                {
                                    id: 2,
                                    code: '3',
                                    type: 'THINKING_CHALLENGE',
                                },
                                {
                                    id: 3,
                                    code: '29',
                                    type: 'PROBLEM_SOLVING_PERCENTAGE',
                                },
                            ],
                        },
                        {
                            id: 3,
                            jeScoreType: 'ACCOUNTABILITY',
                            rationaleDescription: '',
                            points: '76',
                            options: [
                                {
                                    id: 1,
                                    code: 'D-',
                                    type: 'FREEDOM_ACT',
                                },
                                {
                                    id: 2,
                                    code: 'N',
                                    type: 'AREA_IMPACT',
                                },
                                {
                                    id: 3,
                                    code: 'IV+',
                                    type: 'NATURE_IMPACT',
                                },
                            ],
                        },
                    ],
                },
            },
            {
                title: '02.25.2021 CL daily smoke loc test job profiles',
                jobFamily: 'HE',
                jobSubFamily: 'HEA',
                jobRoleTypeId: 'HEA01',
                familyName: 'Health and Environment',
                subFamilyName: 'Environmental Health',
                profileType: Kf.LevelType.CUSTOM,
                id: '92625',
                grade: {
                    standardHayGrade: '14',
                },
                expandable: false,
                shortProfile: 'A1',
                haypoints: {
                    totalPoints: 298,
                    jescores: [
                        {
                            id: 1,
                            jeScoreType: 'KNOW_HOW',
                            rationaleDescription: '',
                            points: '175',
                            options: [
                                {
                                    id: 1,
                                    code: 'E-',
                                    type: 'PRACTICAL_TECHNICAL_KNOWLEDGE',
                                },
                                {
                                    id: 2,
                                    code: 'I',
                                    type: 'MANAGERIAL_KNOWLEDGE',
                                },
                                {
                                    id: 3,
                                    code: '2',
                                    type: 'COMMUNICATION_INFLUENCING_SKILL',
                                },
                            ],
                        },
                        {
                            id: 2,
                            jeScoreType: 'PROBLEM_SOLVING',
                            rationaleDescription: '',
                            points: '57',
                            options: [
                                {
                                    id: 1,
                                    code: 'D+',
                                    type: 'FREEDOM_THINK',
                                },
                                {
                                    id: 2,
                                    code: '3',
                                    type: 'THINKING_CHALLENGE',
                                },
                                {
                                    id: 3,
                                    code: '33',
                                    type: 'PROBLEM_SOLVING_PERCENTAGE',
                                },
                            ],
                        },
                        {
                            id: 3,
                            jeScoreType: 'ACCOUNTABILITY',
                            rationaleDescription: '',
                            points: '66',
                            options: [
                                {
                                    id: 1,
                                    code: 'D-',
                                    type: 'FREEDOM_ACT',
                                },
                                {
                                    id: 2,
                                    code: 'N',
                                    type: 'AREA_IMPACT',
                                },
                                {
                                    id: 3,
                                    code: 'IV',
                                    type: 'NATURE_IMPACT',
                                },
                            ],
                        },
                    ],
                },
            },
        ],
        paging: {
            pageIndex: 1,
            pageSize: 20,
            totalPages: 1,
            totalShowRecords: 2,
            totalResultRecords: 2,
        },
    };

    export const mockDbDataWithSubProfiles = [
        {
            ClientJobId: null,
            SortField: accountManagerCommercialBanking,
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: accountManagerCommercialBanking,
            MinGrade: 15,
            MaxGrade: 18,
            Midpoint: 16,
            HayReferenceLevel: null,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'ROLE',
            ProfileType: 0,
            ShortProfile: null,
            HayPoints: null,
            JELineScore: null,
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110821,
            SortField: 'Account Manager Commercial BankingAccount Manager Commercial Banking I',
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: 'Account Manager Commercial Banking I',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 15,
            HayReferenceLevel: 15,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'BEST_IN_CLASS',
            ProfileType: 2,
            ShortProfile: 'A2',
            HayPoints: 353,
            JELineScore: 'D+ I 3 200  D 3+ (33%) 66  D- N V-   87    353',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110822,
            SortField: 'Account Manager Commercial BankingAccount Manager Commercial Banking II',
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: 'Account Manager Commercial Banking II',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 16,
            HayReferenceLevel: 16,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'BEST_IN_CLASS',
            ProfileType: 2,
            ShortProfile: 'A2',
            HayPoints: 432,
            JELineScore: 'E I 3 230  E 3+ (38%) 87  D+  N  V  115    432            ',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110823,
            SortField: 'Account Manager Commercial BankingAccount Manager Commercial Banking III',
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: 'Account Manager Commercial Banking III',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 17,
            HayReferenceLevel: 17,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'BEST_IN_CLASS',
            ProfileType: 2,
            ShortProfile: 'A2',
            HayPoints: 466,
            JELineScore: 'E+ I 3 264  E 3+ (38%) 100  E-  N  V  132    496',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110824,
            SortField: 'Account Manager Commercial BankingAccount Manager Commercial Banking IV',
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: 'Account Manager Commercial Banking IV',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 18,
            HayReferenceLevel: 18,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'BEST_IN_CLASS',
            ProfileType: 2,
            ShortProfile: 'A2',
            HayPoints: 571,
            JELineScore: 'F- I+ 3 304  E 3+ (38%) 115  E- N V+  152    571',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
    ];

    export const mockDbDataIncldingBoxProfiles = [
        {
            ClientJobId: null,
            SortField: accountManagerCommercialBanking,
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: accountManagerCommercialBanking,
            MinGrade: 15,
            MaxGrade: 18,
            Midpoint: 16,
            HayReferenceLevel: null,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'ROLE',
            ProfileType: 0,
            ShortProfile: null,
            HayPoints: null,
            JELineScore: null,
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110821,
            SortField: 'Account Manager Commercial BankingAccount Manager Commercial Banking I',
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: 'Account Manager Commercial Banking I',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 15,
            HayReferenceLevel: 15,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'BEST_IN_CLASS',
            ProfileType: 2,
            ShortProfile: 'A2',
            HayPoints: 353,
            JELineScore: 'D+ I 3 200  D 3+ (33%) 66  D- N V-   87    353',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110822,
            SortField: 'Account Manager Commercial BankingAccount Manager Commercial Banking II',
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: 'Account Manager Commercial Banking II',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 16,
            HayReferenceLevel: 16,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'BEST_IN_CLASS',
            ProfileType: 2,
            ShortProfile: 'A2',
            HayPoints: 432,
            JELineScore: 'E I 3 230  E 3+ (38%) 87  D+  N  V  115    432            ',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110853,
            SortField: 'Administration/Support/Service - Clerical Services - Entry-Level Professional I',
            ParentClientJobID: null,
            JobRoleTypeID: 'ASA00',
            JobName: 'Administration/Support/Service - Clerical Services - Entry-Level Professional I',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 14,
            HayReferenceLevel: 14,
            JobFamilyID: 'AS',
            JobFamilyName: administration,
            JobSubFamilyID: 'ASA',
            JobSubFamilyName: clerical,
            LevelType: 'BOX-PROFILE',
            ProfileType: 5,
            ShortProfile: 'A2',
            HayPoints: 308,
            JELineScore: 'E I 1  175  D+ 3 33  57  D N IV  76      308',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
    ];
    export const mockDbDataIncludingJobProfiles = [
        {
            ClientJobId: null,
            SortField: 'Adhesive Bonding Machine Operators and Tenders',
            ParentClientJobID: null,
            JobRoleTypeID: 'PRA01',
            JobName: 'Adhesive Bonding Machine Operators and Tenders',
            MinGrade: 8,
            MaxGrade: 11,
            Midpoint: 9,
            HayReferenceLevel: null,
            JobFamilyID: 'PR',
            JobFamilyName: 'Core - Production',
            JobSubFamilyID: 'PRA',
            JobSubFamilyName: 'Production',
            LevelType: 'ROLE',
            ProfileType: 0,
            ShortProfile: null,
            HayPoints: null,
            JELineScore: null,
            TotalRoleNumber: 341,
            TotalResultRecords: 1148,
            TotalShowRecords: 341,
        },
        {
            ClientJobId: 102875,
            SortField: 'Adhesive Bonding Machine Operators and TendersAdhesive Bonding Machine Operators and Tenders I',
            ParentClientJobID: 101548,
            JobRoleTypeID: 'PRA01',
            JobName: 'Adhesive Bonding Machine Operators and Tenders I',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 8,
            HayReferenceLevel: 8,
            JobFamilyID: 'PR',
            JobFamilyName: 'Core - Production',
            JobSubFamilyID: 'PRA',
            JobSubFamilyName: 'Production',
            LevelType: 'O_NET',
            ProfileType: 3,
            ShortProfile: 'A3',
            HayPoints: 107,
            JELineScore: 'B+ I- 1 76  B 2 (16%) 12  B- N II+ 19    107',
            TotalRoleNumber: 341,
            TotalResultRecords: 1148,
            TotalShowRecords: 341,
        },
        {
            ClientJobId: 103032,
            SortField: 'Adhesive Bonding Machine Operators and TendersAdhesive Bonding Machine Operators and Tenders II',
            ParentClientJobID: 101549,
            JobRoleTypeID: 'PRA01',
            JobName: 'Adhesive Bonding Machine Operators and Tenders II',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 9,
            HayReferenceLevel: 9,
            JobFamilyID: 'PR',
            JobFamilyName: 'Core - Production',
            JobSubFamilyID: 'PRA',
            JobSubFamilyName: 'Production',
            LevelType: 'O_NET',
            ProfileType: 3,
            ShortProfile: 'A3',
            HayPoints: 128,
            JELineScore: 'C- I 1 87  B+ 2 (19%) 16  B N III 25    128',
            TotalRoleNumber: 341,
            TotalResultRecords: 1148,
            TotalShowRecords: 341,
        },
        {
            ClientJobId: 103033,
            SortField: 'Adhesive Bonding Machine Operators and TendersAdhesive Bonding Machine Operators and Tenders III',
            ParentClientJobID: 101550,
            JobRoleTypeID: 'PRA01',
            JobName: 'Adhesive Bonding Machine Operators and Tenders III',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 10,
            HayReferenceLevel: 10,
            JobFamilyID: 'PR',
            JobFamilyName: 'Core - Production',
            JobSubFamilyID: 'PRA',
            JobSubFamilyName: 'Production',
            LevelType: 'O_NET',
            ProfileType: 3,
            ShortProfile: 'A3',
            HayPoints: 148,
            JELineScore: 'C I 1 100  B+ 2 (19%) 19  B N III+ 29    148',
            TotalRoleNumber: 341,
            TotalResultRecords: 1148,
            TotalShowRecords: 341,
        },
        {
            ClientJobId: 103190,
            SortField: 'Adhesive Bonding Machine Operators and TendersAdhesive Bonding Machine Operators and Tenders IV',
            ParentClientJobID: 101551,
            JobRoleTypeID: 'PRA01',
            JobName: 'Adhesive Bonding Machine Operators and Tenders IV',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 11,
            HayReferenceLevel: 11,
            JobFamilyID: 'PR',
            JobFamilyName: 'Core - Production',
            JobSubFamilyID: 'PRA',
            JobSubFamilyName: 'Production',
            LevelType: 'O_NET',
            ProfileType: 3,
            ShortProfile: 'A3',
            HayPoints: 178,
            JELineScore: 'C+ I 1 115  C 2+ (22%) 25  C- N III+ 38    178',
            TotalRoleNumber: 341,
            TotalResultRecords: 1148,
            TotalShowRecords: 341,
        },
    ];
    export const mockDbDataIncldingCXOProfiles = [
        {
            ClientJobId: null,
            SortField: accountManagerCommercialBanking,
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: accountManagerCommercialBanking,
            MinGrade: 15,
            MaxGrade: 18,
            Midpoint: 16,
            HayReferenceLevel: null,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'ROLE',
            ProfileType: 0,
            ShortProfile: null,
            HayPoints: null,
            JELineScore: null,
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110821,
            SortField: 'Account Manager Commercial BankingAccount Manager Commercial Banking I',
            ParentClientJobID: null,
            JobRoleTypeID: 'MBA01',
            JobName: 'Account Manager Commercial Banking I',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 15,
            HayReferenceLevel: 15,
            JobFamilyID: 'MB',
            JobFamilyName: midTierCommercialBanking,
            JobSubFamilyID: 'MBA',
            JobSubFamilyName: midTierCommercialBanking,
            LevelType: 'BEST_IN_CLASS',
            ProfileType: 2,
            ShortProfile: 'A2',
            HayPoints: 353,
            JELineScore: 'D+ I 3 200  D 3+ (33%) 66  D- N V-   87    353',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
        {
            ClientJobId: 110853,
            SortField: 'Administration/Support/Service - Clerical Services - Entry-Level Professional I',
            ParentClientJobID: null,
            JobRoleTypeID: 'ASA00',
            JobName: 'Administration/Support/Service - Clerical Services - Entry-Level Professional I',
            MinGrade: null,
            MaxGrade: null,
            Midpoint: 14,
            HayReferenceLevel: 14,
            JobFamilyID: 'AS',
            JobFamilyName: administration,
            JobSubFamilyID: 'ASA',
            JobSubFamilyName: clerical,
            LevelType: 'CXO-PROFILE',
            ProfileType: 5,
            ShortProfile: 'A2',
            HayPoints: 308,
            JELineScore: 'E I 1  175  D+ 3 33  57  D N IV  76      308',
            TotalRoleNumber: 624,
            TotalResultRecords: 2297,
            TotalShowRecords: 748,
        },
    ];

    export const expectedCXOProfilesRolesList = [
        {
            title: 'Account Manager Commercial Banking',
            jobFamily: 'MB',
            jobSubFamily: 'MBA',
            jobRoleTypeId: 'MBA01',
            familyName: 'Mid-tier / Commercial Banking',
            subFamilyName: 'Mid-tier / Commercial Banking',
            profileType: 'BEST_IN_CLASS',
            grade: { min: 15, max: 18 },
            expandable: true,
            profiles: [
                {
                    title: 'Account Manager Commercial Banking I',
                    jobFamily: 'MB',
                    jobSubFamily: 'MBA',
                    jobRoleTypeId: 'MBA01',
                    familyName: 'Mid-tier / Commercial Banking',
                    subFamilyName: 'Mid-tier / Commercial Banking',
                    profileType: 'BEST_IN_CLASS',
                    id: '110821',
                    shortProfile: 'A2',
                    haypoints: {
                        totalPoints: 353,
                        jescores: [
                            {
                                id: 1,
                                jeScoreType: 'KNOW_HOW',
                                rationaleDescription: '',
                                points: '200',
                                options: [
                                    { id: 1, code: 'D+', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                                    { id: 2, code: 'I', type: 'MANAGERIAL_KNOWLEDGE' },
                                    { id: 3, code: '3', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                                ],
                            },
                            {
                                id: 2,
                                jeScoreType: 'PROBLEM_SOLVING',
                                rationaleDescription: '',
                                points: '66',
                                options: [
                                    { id: 1, code: 'D', type: 'FREEDOM_THINK' },
                                    { id: 2, code: '3+', type: 'THINKING_CHALLENGE' },
                                    { id: 3, code: '33', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                                ],
                            },
                            {
                                id: 3,
                                jeScoreType: 'ACCOUNTABILITY',
                                rationaleDescription: '',
                                points: '87',
                                options: [
                                    { id: 1, code: 'D-', type: 'FREEDOM_ACT' },
                                    { id: 2, code: 'N', type: 'AREA_IMPACT' },
                                    { id: 3, code: 'V-', type: 'NATURE_IMPACT' },
                                ],
                            },
                        ],
                    },
                    standardHayGrade: '15',
                },
            ],
        },
        {
            title: 'Administration/Support/Service - Clerical Services - Entry-Level Professional I',
            jobFamily: 'AS',
            jobSubFamily: 'ASA',
            jobRoleTypeId: 'ASA00',
            familyName: 'Administration / Support / Service',
            subFamilyName: 'Clerical Services',
            profileType: 'BEST_IN_CLASS',
            id: '110853',
            grade: { min: null, max: null },
            expandable: false,
            shortProfile: 'A2',
            haypoints: {
                totalPoints: 308,
                jescores: [
                    {
                        id: 1,
                        jeScoreType: 'KNOW_HOW',
                        rationaleDescription: '',
                        points: '175',
                        options: [
                            { id: 1, code: 'E', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                            { id: 2, code: 'I', type: 'MANAGERIAL_KNOWLEDGE' },
                            { id: 3, code: '1', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                        ],
                    },
                    {
                        id: 2,
                        jeScoreType: 'PROBLEM_SOLVING',
                        rationaleDescription: '',
                        points: '57',
                        options: [
                            { id: 1, code: 'D+', type: 'FREEDOM_THINK' },
                            { id: 2, code: '3', type: 'THINKING_CHALLENGE' },
                            { id: 3, code: '33', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                        ],
                    },
                    {
                        id: 3,
                        jeScoreType: 'ACCOUNTABILITY',
                        rationaleDescription: '',
                        points: '76',
                        options: [
                            { id: 1, code: 'D', type: 'FREEDOM_ACT' },
                            { id: 2, code: 'N', type: 'AREA_IMPACT' },
                            { id: 3, code: 'IV', type: 'NATURE_IMPACT' },
                        ],
                    },
                ],
            },
        },
    ];

    export const expectedBoxProfilesRolesList = [
        {
            title: 'Account Manager Commercial Banking',
            jobFamily: 'MB',
            jobSubFamily: 'MBA',
            jobRoleTypeId: 'MBA01',
            familyName: 'Mid-tier / Commercial Banking',
            subFamilyName: 'Mid-tier / Commercial Banking',
            profileType: 'BEST_IN_CLASS',
            grade: { min: 15, max: 18 },
            expandable: true,
            profiles: [
                {
                    title: 'Account Manager Commercial Banking I',
                    jobFamily: 'MB',
                    jobSubFamily: 'MBA',
                    jobRoleTypeId: 'MBA01',
                    familyName: 'Mid-tier / Commercial Banking',
                    subFamilyName: 'Mid-tier / Commercial Banking',
                    profileType: 'BEST_IN_CLASS',
                    id: '110821',
                    shortProfile: 'A2',
                    haypoints: {
                        totalPoints: 353,
                        jescores: [
                            {
                                id: 1,
                                jeScoreType: 'KNOW_HOW',
                                rationaleDescription: '',
                                points: '200',
                                options: [
                                    { id: 1, code: 'D+', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                                    { id: 2, code: 'I', type: 'MANAGERIAL_KNOWLEDGE' },
                                    { id: 3, code: '3', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                                ],
                            },
                            {
                                id: 2,
                                jeScoreType: 'PROBLEM_SOLVING',
                                rationaleDescription: '',
                                points: '66',
                                options: [
                                    { id: 1, code: 'D', type: 'FREEDOM_THINK' },
                                    { id: 2, code: '3+', type: 'THINKING_CHALLENGE' },
                                    { id: 3, code: '33', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                                ],
                            },
                            {
                                id: 3,
                                jeScoreType: 'ACCOUNTABILITY',
                                rationaleDescription: '',
                                points: '87',
                                options: [
                                    { id: 1, code: 'D-', type: 'FREEDOM_ACT' },
                                    { id: 2, code: 'N', type: 'AREA_IMPACT' },
                                    { id: 3, code: 'V-', type: 'NATURE_IMPACT' },
                                ],
                            },
                        ],
                    },
                    standardHayGrade: '15',
                },
                {
                    title: 'Account Manager Commercial Banking II',
                    jobFamily: 'MB',
                    jobSubFamily: 'MBA',
                    jobRoleTypeId: 'MBA01',
                    familyName: 'Mid-tier / Commercial Banking',
                    subFamilyName: 'Mid-tier / Commercial Banking',
                    profileType: 'BEST_IN_CLASS',
                    id: '110822',
                    shortProfile: 'A2',
                    haypoints: {
                        totalPoints: 432,
                        jescores: [
                            {
                                id: 1,
                                jeScoreType: 'KNOW_HOW',
                                rationaleDescription: '',
                                points: '230',
                                options: [
                                    { id: 1, code: 'E', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                                    { id: 2, code: 'I', type: 'MANAGERIAL_KNOWLEDGE' },
                                    { id: 3, code: '3', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                                ],
                            },
                            {
                                id: 2,
                                jeScoreType: 'PROBLEM_SOLVING',
                                rationaleDescription: '',
                                points: '87',
                                options: [
                                    { id: 1, code: 'E', type: 'FREEDOM_THINK' },
                                    { id: 2, code: '3+', type: 'THINKING_CHALLENGE' },
                                    { id: 3, code: '38', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                                ],
                            },
                            {
                                id: 3,
                                jeScoreType: 'ACCOUNTABILITY',
                                rationaleDescription: '',
                                points: '115',
                                options: [
                                    { id: 1, code: 'D+', type: 'FREEDOM_ACT' },
                                    { id: 2, code: 'N', type: 'AREA_IMPACT' },
                                    { id: 3, code: 'V', type: 'NATURE_IMPACT' },
                                ],
                            },
                        ],
                    },
                    standardHayGrade: '16',
                },
            ],
        },
        {
            title: 'Administration/Support/Service - Clerical Services - Entry-Level Professional I',
            jobFamily: 'AS',
            jobSubFamily: 'ASA',
            jobRoleTypeId: 'ASA00',
            familyName: 'Administration / Support / Service',
            subFamilyName: 'Clerical Services',
            profileType: 'BOX-PROFILE',
            id: '110853',
            grade: { standardHayGrade: '14' },
            expandable: false,
            shortProfile: 'A2',
            haypoints: {
                totalPoints: 308,
                jescores: [
                    {
                        id: 1,
                        jeScoreType: 'KNOW_HOW',
                        rationaleDescription: '',
                        points: '175',
                        options: [
                            {
                                id: 1,
                                code: 'E',
                                type: 'PRACTICAL_TECHNICAL_KNOWLEDGE',
                            },
                            {
                                id: 2,
                                code: 'I',
                                type: 'MANAGERIAL_KNOWLEDGE',
                            },
                            {
                                id: 3,
                                code: '1',
                                type: 'COMMUNICATION_INFLUENCING_SKILL',
                            },
                        ],
                    },
                    {
                        id: 2,
                        jeScoreType: 'PROBLEM_SOLVING',
                        rationaleDescription: '',
                        points: '57',
                        options: [
                            {
                                id: 1,
                                code: 'D+',
                                type: 'FREEDOM_THINK',
                            },
                            {
                                id: 2,
                                code: '3',
                                type: 'THINKING_CHALLENGE',
                            },
                            {
                                id: 3,
                                code: '33',
                                type: 'PROBLEM_SOLVING_PERCENTAGE',
                            },
                        ],
                    },
                    {
                        id: 3,
                        jeScoreType: 'ACCOUNTABILITY',
                        rationaleDescription: '',
                        points: '76',
                        options: [
                            {
                                id: 1,
                                code: 'D',
                                type: 'FREEDOM_ACT',
                            },
                            {
                                id: 2,
                                code: 'N',
                                type: 'AREA_IMPACT',
                            },
                            {
                                id: 3,
                                code: 'IV',
                                type: 'NATURE_IMPACT',
                            },
                        ],
                    },
                ],
            },
        },
    ];

    export const expectedJobProfilesRolesList = [
        {
            title: 'Adhesive Bonding Machine Operators and Tenders',
            jobFamily: 'PR',
            jobSubFamily: 'PRA',
            jobRoleTypeId: 'PRA01',
            familyName: 'Core - Production',
            subFamilyName: 'Production',
            profileType: 'O_NET',
            grade: { min: 8, max: 11 },
            expandable: true,
            profiles: [
                {
                    title: 'Adhesive Bonding Machine Operators and Tenders I',
                    jobFamily: 'PR',
                    jobSubFamily: 'PRA',
                    jobRoleTypeId: 'PRA01',
                    familyName: 'Core - Production',
                    subFamilyName: 'Production',
                    profileType: 'O_NET',
                    id: '102875',
                    shortProfile: 'A3',
                    haypoints: {
                        totalPoints: 107,
                        jescores: [
                            {
                                id: 1,
                                jeScoreType: 'KNOW_HOW',
                                rationaleDescription: '',
                                points: '76',
                                options: [
                                    { id: 1, code: 'B+', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                                    { id: 2, code: 'I-', type: 'MANAGERIAL_KNOWLEDGE' },
                                    { id: 3, code: '1', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                                ],
                            },
                            {
                                id: 2,
                                jeScoreType: 'PROBLEM_SOLVING',
                                rationaleDescription: '',
                                points: '12',
                                options: [
                                    { id: 1, code: 'B', type: 'FREEDOM_THINK' },
                                    { id: 2, code: '2', type: 'THINKING_CHALLENGE' },
                                    { id: 3, code: '16', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                                ],
                            },
                            {
                                id: 3,
                                jeScoreType: 'ACCOUNTABILITY',
                                rationaleDescription: '',
                                points: '19',
                                options: [
                                    { id: 1, code: 'B-', type: 'FREEDOM_ACT' },
                                    { id: 2, code: 'N', type: 'AREA_IMPACT' },
                                    { id: 3, code: 'II+', type: 'NATURE_IMPACT' },
                                ],
                            },
                        ],
                    },
                    standardHayGrade: '8',
                },
                {
                    title: 'Adhesive Bonding Machine Operators and Tenders II',
                    jobFamily: 'PR',
                    jobSubFamily: 'PRA',
                    jobRoleTypeId: 'PRA01',
                    familyName: 'Core - Production',
                    subFamilyName: 'Production',
                    profileType: 'O_NET',
                    id: '103032',
                    shortProfile: 'A3',
                    haypoints: {
                        totalPoints: 128,
                        jescores: [
                            {
                                id: 1,
                                jeScoreType: 'KNOW_HOW',
                                rationaleDescription: '',
                                points: '87',
                                options: [
                                    { id: 1, code: 'C-', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                                    { id: 2, code: 'I', type: 'MANAGERIAL_KNOWLEDGE' },
                                    { id: 3, code: '1', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                                ],
                            },
                            {
                                id: 2,
                                jeScoreType: 'PROBLEM_SOLVING',
                                rationaleDescription: '',
                                points: '16',
                                options: [
                                    { id: 1, code: 'B+', type: 'FREEDOM_THINK' },
                                    { id: 2, code: '2', type: 'THINKING_CHALLENGE' },
                                    { id: 3, code: '19', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                                ],
                            },
                            {
                                id: 3,
                                jeScoreType: 'ACCOUNTABILITY',
                                rationaleDescription: '',
                                points: '25',
                                options: [
                                    { id: 1, code: 'B', type: 'FREEDOM_ACT' },
                                    { id: 2, code: 'N', type: 'AREA_IMPACT' },
                                    { id: 3, code: 'III', type: 'NATURE_IMPACT' },
                                ],
                            },
                        ],
                    },
                    standardHayGrade: '9',
                },
                {
                    title: 'Adhesive Bonding Machine Operators and Tenders III',
                    jobFamily: 'PR',
                    jobSubFamily: 'PRA',
                    jobRoleTypeId: 'PRA01',
                    familyName: 'Core - Production',
                    subFamilyName: 'Production',
                    profileType: 'O_NET',
                    id: '103033',
                    shortProfile: 'A3',
                    haypoints: {
                        totalPoints: 148,
                        jescores: [
                            {
                                id: 1,
                                jeScoreType: 'KNOW_HOW',
                                rationaleDescription: '',
                                points: '100',
                                options: [
                                    { id: 1, code: 'C', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                                    { id: 2, code: 'I', type: 'MANAGERIAL_KNOWLEDGE' },
                                    { id: 3, code: '1', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                                ],
                            },
                            {
                                id: 2,
                                jeScoreType: 'PROBLEM_SOLVING',
                                rationaleDescription: '',
                                points: '19',
                                options: [
                                    { id: 1, code: 'B+', type: 'FREEDOM_THINK' },
                                    { id: 2, code: '2', type: 'THINKING_CHALLENGE' },
                                    { id: 3, code: '19', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                                ],
                            },
                            {
                                id: 3,
                                jeScoreType: 'ACCOUNTABILITY',
                                rationaleDescription: '',
                                points: '29',
                                options: [
                                    { id: 1, code: 'B', type: 'FREEDOM_ACT' },
                                    { id: 2, code: 'N', type: 'AREA_IMPACT' },
                                    { id: 3, code: 'III+', type: 'NATURE_IMPACT' },
                                ],
                            },
                        ],
                    },
                    standardHayGrade: '10',
                },
                {
                    title: 'Adhesive Bonding Machine Operators and Tenders IV',
                    jobFamily: 'PR',
                    jobSubFamily: 'PRA',
                    jobRoleTypeId: 'PRA01',
                    familyName: 'Core - Production',
                    subFamilyName: 'Production',
                    profileType: 'O_NET',
                    id: '103190',
                    shortProfile: 'A3',
                    haypoints: {
                        totalPoints: 178,
                        jescores: [
                            {
                                id: 1,
                                jeScoreType: 'KNOW_HOW',
                                rationaleDescription: '',
                                points: '115',
                                options: [
                                    { id: 1, code: 'C+', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                                    { id: 2, code: 'I', type: 'MANAGERIAL_KNOWLEDGE' },
                                    { id: 3, code: '1', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                                ],
                            },
                            {
                                id: 2,
                                jeScoreType: 'PROBLEM_SOLVING',
                                rationaleDescription: '',
                                points: '25',
                                options: [
                                    { id: 1, code: 'C', type: 'FREEDOM_THINK' },
                                    { id: 2, code: '2+', type: 'THINKING_CHALLENGE' },
                                    { id: 3, code: '22', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                                ],
                            },
                            {
                                id: 3,
                                jeScoreType: 'ACCOUNTABILITY',
                                rationaleDescription: '',
                                points: '38',
                                options: [
                                    { id: 1, code: 'C-', type: 'FREEDOM_ACT' },
                                    { id: 2, code: 'N', type: 'AREA_IMPACT' },
                                    { id: 3, code: 'III+', type: 'NATURE_IMPACT' },
                                ],
                            },
                        ],
                    },
                    standardHayGrade: '11',
                },
            ],
        },
    ];

    export const expectedRolesWithSubProfiles = {
        roles: [
            {
                title: accountManagerCommercialBanking,
                jobFamily: 'MB',
                jobSubFamily: 'MBA',
                jobRoleTypeId: 'MBA01',
                familyName: midTierCommercialBanking,
                subFamilyName: midTierCommercialBanking,
                profileType: 'BEST_IN_CLASS',
                grade: {
                    min: 15,
                    max: 18,
                },
                expandable: true,
                profiles: [
                    {
                        title: 'Account Manager Commercial Banking I',
                        jobFamily: 'MB',
                        jobSubFamily: 'MBA',
                        jobRoleTypeId: 'MBA01',
                        familyName: midTierCommercialBanking,
                        subFamilyName: midTierCommercialBanking,
                        profileType: 'BEST_IN_CLASS',
                        id: '110821',
                        shortProfile: 'A2',
                        haypoints: {
                            totalPoints: 353,
                            jescores: [
                                {
                                    id: 1,
                                    jeScoreType: 'KNOW_HOW',
                                    rationaleDescription: '',
                                    points: '200',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'D+',
                                            type: 'PRACTICAL_TECHNICAL_KNOWLEDGE',
                                        },
                                        {
                                            id: 2,
                                            code: 'I',
                                            type: 'MANAGERIAL_KNOWLEDGE',
                                        },
                                        {
                                            id: 3,
                                            code: '3',
                                            type: 'COMMUNICATION_INFLUENCING_SKILL',
                                        },
                                    ],
                                },
                                {
                                    id: 2,
                                    jeScoreType: 'PROBLEM_SOLVING',
                                    rationaleDescription: '',
                                    points: '66',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'D',
                                            type: 'FREEDOM_THINK',
                                        },
                                        {
                                            id: 2,
                                            code: '3+',
                                            type: 'THINKING_CHALLENGE',
                                        },
                                        {
                                            id: 3,
                                            code: '33',
                                            type: 'PROBLEM_SOLVING_PERCENTAGE',
                                        },
                                    ],
                                },
                                {
                                    id: 3,
                                    jeScoreType: 'ACCOUNTABILITY',
                                    rationaleDescription: '',
                                    points: '87',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'D-',
                                            type: 'FREEDOM_ACT',
                                        },
                                        {
                                            id: 2,
                                            code: 'N',
                                            type: 'AREA_IMPACT',
                                        },
                                        {
                                            id: 3,
                                            code: 'V-',
                                            type: 'NATURE_IMPACT',
                                        },
                                    ],
                                },
                            ],
                        },
                        standardHayGrade: '15',
                    },
                    {
                        title: 'Account Manager Commercial Banking II',
                        jobFamily: 'MB',
                        jobSubFamily: 'MBA',
                        jobRoleTypeId: 'MBA01',
                        familyName: midTierCommercialBanking,
                        subFamilyName: midTierCommercialBanking,
                        profileType: 'BEST_IN_CLASS',
                        id: '110822',
                        shortProfile: 'A2',
                        haypoints: {
                            totalPoints: 432,
                            jescores: [
                                {
                                    id: 1,
                                    jeScoreType: 'KNOW_HOW',
                                    rationaleDescription: '',
                                    points: '230',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'E',
                                            type: 'PRACTICAL_TECHNICAL_KNOWLEDGE',
                                        },
                                        {
                                            id: 2,
                                            code: 'I',
                                            type: 'MANAGERIAL_KNOWLEDGE',
                                        },
                                        {
                                            id: 3,
                                            code: '3',
                                            type: 'COMMUNICATION_INFLUENCING_SKILL',
                                        },
                                    ],
                                },
                                {
                                    id: 2,
                                    jeScoreType: 'PROBLEM_SOLVING',
                                    rationaleDescription: '',
                                    points: '87',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'E',
                                            type: 'FREEDOM_THINK',
                                        },
                                        {
                                            id: 2,
                                            code: '3+',
                                            type: 'THINKING_CHALLENGE',
                                        },
                                        {
                                            id: 3,
                                            code: '38',
                                            type: 'PROBLEM_SOLVING_PERCENTAGE',
                                        },
                                    ],
                                },
                                {
                                    id: 3,
                                    jeScoreType: 'ACCOUNTABILITY',
                                    rationaleDescription: '',
                                    points: '115',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'D+',
                                            type: 'FREEDOM_ACT',
                                        },
                                        {
                                            id: 2,
                                            code: 'N',
                                            type: 'AREA_IMPACT',
                                        },
                                        {
                                            id: 3,
                                            code: 'V',
                                            type: 'NATURE_IMPACT',
                                        },
                                    ],
                                },
                            ],
                        },
                        standardHayGrade: '16',
                    },
                    {
                        title: 'Account Manager Commercial Banking III',
                        jobFamily: 'MB',
                        jobSubFamily: 'MBA',
                        jobRoleTypeId: 'MBA01',
                        familyName: midTierCommercialBanking,
                        subFamilyName: midTierCommercialBanking,
                        profileType: 'BEST_IN_CLASS',
                        id: '110823',
                        shortProfile: 'A2',
                        haypoints: {
                            totalPoints: 466,
                            jescores: [
                                {
                                    id: 1,
                                    jeScoreType: 'KNOW_HOW',
                                    rationaleDescription: '',
                                    points: '264',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'E+',
                                            type: 'PRACTICAL_TECHNICAL_KNOWLEDGE',
                                        },
                                        {
                                            id: 2,
                                            code: 'I',
                                            type: 'MANAGERIAL_KNOWLEDGE',
                                        },
                                        {
                                            id: 3,
                                            code: '3',
                                            type: 'COMMUNICATION_INFLUENCING_SKILL',
                                        },
                                    ],
                                },
                                {
                                    id: 2,
                                    jeScoreType: 'PROBLEM_SOLVING',
                                    rationaleDescription: '',
                                    points: '100',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'E',
                                            type: 'FREEDOM_THINK',
                                        },
                                        {
                                            id: 2,
                                            code: '3+',
                                            type: 'THINKING_CHALLENGE',
                                        },
                                        {
                                            id: 3,
                                            code: '38',
                                            type: 'PROBLEM_SOLVING_PERCENTAGE',
                                        },
                                    ],
                                },
                                {
                                    id: 3,
                                    jeScoreType: 'ACCOUNTABILITY',
                                    rationaleDescription: '',
                                    points: '132',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'E-',
                                            type: 'FREEDOM_ACT',
                                        },
                                        {
                                            id: 2,
                                            code: 'N',
                                            type: 'AREA_IMPACT',
                                        },
                                        {
                                            id: 3,
                                            code: 'V',
                                            type: 'NATURE_IMPACT',
                                        },
                                    ],
                                },
                            ],
                        },
                        standardHayGrade: '17',
                    },
                    {
                        title: 'Account Manager Commercial Banking IV',
                        jobFamily: 'MB',
                        jobSubFamily: 'MBA',
                        jobRoleTypeId: 'MBA01',
                        familyName: midTierCommercialBanking,
                        subFamilyName: midTierCommercialBanking,
                        profileType: 'BEST_IN_CLASS',
                        id: '110824',
                        shortProfile: 'A2',
                        haypoints: {
                            totalPoints: 571,
                            jescores: [
                                {
                                    id: 1,
                                    jeScoreType: 'KNOW_HOW',
                                    rationaleDescription: '',
                                    points: '304',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'F-',
                                            type: 'PRACTICAL_TECHNICAL_KNOWLEDGE',
                                        },
                                        {
                                            id: 2,
                                            code: 'I+',
                                            type: 'MANAGERIAL_KNOWLEDGE',
                                        },
                                        {
                                            id: 3,
                                            code: '3',
                                            type: 'COMMUNICATION_INFLUENCING_SKILL',
                                        },
                                    ],
                                },
                                {
                                    id: 2,
                                    jeScoreType: 'PROBLEM_SOLVING',
                                    rationaleDescription: '',
                                    points: '115',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'E',
                                            type: 'FREEDOM_THINK',
                                        },
                                        {
                                            id: 2,
                                            code: '3+',
                                            type: 'THINKING_CHALLENGE',
                                        },
                                        {
                                            id: 3,
                                            code: '38',
                                            type: 'PROBLEM_SOLVING_PERCENTAGE',
                                        },
                                    ],
                                },
                                {
                                    id: 3,
                                    jeScoreType: 'ACCOUNTABILITY',
                                    rationaleDescription: '',
                                    points: '152',
                                    options: [
                                        {
                                            id: 1,
                                            code: 'E-',
                                            type: 'FREEDOM_ACT',
                                        },
                                        {
                                            id: 2,
                                            code: 'N',
                                            type: 'AREA_IMPACT',
                                        },
                                        {
                                            id: 3,
                                            code: 'V+',
                                            type: 'NATURE_IMPACT',
                                        },
                                    ],
                                },
                            ],
                        },
                        standardHayGrade: '18',
                    },
                ],
            },
        ],
    };

    export const singleDbRecordTypeRole = {
        ClientJobId: null,
        SortField: accountManagerCommercialBanking,
        ParentClientJobID: null,
        JobRoleTypeID: 'MBA01',
        JobName: accountManagerCommercialBanking,
        MinGrade: 15,
        MaxGrade: 18,
        Midpoint: 16,
        HayReferenceLevel: null,
        JobFamilyID: 'MB',
        JobFamilyName: midTierCommercialBanking,
        JobSubFamilyID: 'MBA',
        JobSubFamilyName: midTierCommercialBanking,
        LevelType: 'ROLE',
        ProfileType: 0,
        ShortProfile: null,
        HayPoints: null,
        JELineScore: null,
        TotalRoleNumber: 624,
        TotalResultRecords: 2297,
        TotalShowRecords: 748,
    };

    export const commonObjProps = {
        title: singleDbRecordTypeRole.JobName,
        jobFamily: singleDbRecordTypeRole.JobFamilyID,
        jobSubFamily: singleDbRecordTypeRole.JobSubFamilyID,
        jobRoleTypeId: singleDbRecordTypeRole.JobRoleTypeID,
        familyName: singleDbRecordTypeRole.JobFamilyName,
        subFamilyName: singleDbRecordTypeRole.JobSubFamilyName,
        profileType: singleDbRecordTypeRole.LevelType,
    };

    export const expectedRole = {
        title: accountManagerCommercialBanking,
        jobFamily: 'MB',
        jobSubFamily: 'MBA',
        jobRoleTypeId: 'MBA01',
        familyName: midTierCommercialBanking,
        subFamilyName: midTierCommercialBanking,
        profileType: 'ROLE',
        grade: {
            min: 15,
            max: 18,
        },
        expandable: true,
        profiles: [],
    };

    export const rolesDataContainer = {
        rolesList: [],
        rolesHash: {},
        currentRole: null,
    };

    export const singleCXOProfile = [
        {
            ClientJobId: 154969,
            ParentClientJobID: null,
            SortField: 'Business Manager of Managers',
            JobRoleTypeID: 'EMC01',
            JobName: 'Business Manager of Managers',
            MinGrade: 18,
            MaxGrade: 22,
            Midpoint: 20,
            HayReferenceLevel: 20,
            JobFamilyID: 'EM',
            JobFamilyName: 'Executive Management',
            JobSubFamilyID: 'EMC',
            JobSubFamilyName: 'General Management',
            LevelType: 'CXO-PROFILE',
            ProfileType: 2,
            ShortProfile: 'A3',
            HayPoints: 839,
            JELineScore: 'F II 3 400 E 4 (43%) 175 E 3 P 264 839',
            TotalRoleNumber: 0,
            TotalResultRecords: 1,
            TotalShowRecords: 1,
        },
    ];
    export const expecedSingleCXOProfiledata = [
        {
            title: 'Business Manager of Managers',
            jobFamily: 'EM',
            jobSubFamily: 'EMC',
            jobRoleTypeId: 'EMC01',
            familyName: 'Executive Management',
            subFamilyName: 'General Management',
            profileType: 'BEST_IN_CLASS',
            id: '154969',
            grade: { min: 18, max: 22 },
            expandable: false,
            shortProfile: 'A3',
            haypoints: {
                totalPoints: 839,
                jescores: [
                    {
                        id: 1,
                        jeScoreType: 'KNOW_HOW',
                        rationaleDescription: '',
                        points: '400',
                        options: [
                            { id: 1, code: 'F', type: 'PRACTICAL_TECHNICAL_KNOWLEDGE' },
                            { id: 2, code: 'II', type: 'MANAGERIAL_KNOWLEDGE' },
                            { id: 3, code: '3', type: 'COMMUNICATION_INFLUENCING_SKILL' },
                        ],
                    },
                    {
                        id: 2,
                        jeScoreType: 'PROBLEM_SOLVING',
                        rationaleDescription: '',
                        points: '175',
                        options: [
                            { id: 1, code: 'E', type: 'FREEDOM_THINK' },
                            { id: 2, code: '4', type: 'THINKING_CHALLENGE' },
                            { id: 3, code: '43', type: 'PROBLEM_SOLVING_PERCENTAGE' },
                        ],
                    },
                    {
                        id: 3,
                        jeScoreType: 'ACCOUNTABILITY',
                        rationaleDescription: '',
                        points: '264',
                        options: [
                            { id: 1, code: 'E', type: 'FREEDOM_ACT' },
                            { id: 2, code: '3', type: 'AREA_IMPACT' },
                            { id: 3, code: 'P', type: 'NATURE_IMPACT' },
                        ],
                    },
                ],
            },
        },
    ];
}
