export enum ClientAction {
    CREATE_TASK_GROUP = 'CREATE_TASK_GROUP',
    UPDATE_TASK_GROUP = 'UPDATE_TASK_GROUP',
    CANCEL_TASK_GROUP = 'CANCEL_TASK_GROUP',
    ARCHIVE_TASK_GROUP = 'ARCHIVE_TASK_GROUP',
    CLEAR_TASK_GROUP = 'CLEAR_TASK_GROUP',
    CANCEL_TASK = 'CANCEL_TASK',
    RUN_TASK = 'RUN_TASK',
    UPDATE_TASK_GROUP_RESULT = 'UPDATE_TASK_GROUP_RESULT',
    UPDATE_TASK_RESULT = 'UPDATE_TASK_RESULT',
}

export enum TaskStatus {
    QUEUED = 0,
    RUNNING = 1,
    COMPLETED = 2,
    FAILED = 3,
    CANCELED = 5,
    REMOVED = 8,
}

export enum TaskGroupStatus {
    QUEUED = 0,
    IN_PROGRESS = 1,
    POST_PROCESSING = 7,
    COMPLETED = 2,
    FAILED = 3,
    CANCELED = 5,
    ARCHIVED = 6,
    REMOVED = 8,
}
