export const mockMetadata = [
    { id: 1, name: 'Accounting' },
    { id: 2, name: 'Airlines/Aviation' },
    { id: 3, name: 'Alternative Dispute Resolution' },
    { id: 4, name: 'Alternative Medicine' },
    { id: 5, name: 'Animation' },
    { id: 6, name: 'Apparel & Fashion' },
    { id: 7, name: 'Architecture & Planning' },
    { id: 8, name: 'Arts' },
    { id: 9, name: 'Arts and Crafts' },
    { id: 10, name: 'Automotive' },
    { id: 11, name: 'Aviation & Aerospace' },
    { id: 12, name: 'Banking' },
    { id: 13, name: 'Biotechnology' },
    { id: 14, name: 'Broadcast Media' },
    { id: 15, name: 'Building Materials' },
    { id: 16, name: 'Business Supplies and Equipment' },
    { id: 17, name: 'Capital Markets' },
    { id: 18, name: 'Chemicals' },
    { id: 19, name: 'Civic & Social Organization' },
    { id: 20, name: 'Civil Engineering' },
    { id: 21, name: 'Commercial Real Estate' },
    { id: 22, name: 'Computer & Network Security' },
    { id: 23, name: 'Computer Games' },
    { id: 24, name: 'Computer Hardware' },
    { id: 25, name: 'Computer Networking' },
    { id: 26, name: 'Computer Software' },
    { id: 27, name: 'Construction' },
    { id: 28, name: 'Consumer Electronics' },
    { id: 29, name: 'Consumer Goods' },
    { id: 30, name: 'Consumer Services' },
    { id: 31, name: 'Cosmetics' },
    { id: 32, name: 'Credit Unions & Community Banks' },
    { id: 33, name: 'Dairy' },
    { id: 34, name: 'Defense & Space' },
    { id: 35, name: 'Design' },
    { id: 36, name: 'E - Learning' },
    { id: 37, name: 'Education Management' },
    { id: 38, name: 'Electrical/Electronic Manufacturing' },
    { id: 39, name: 'Entertainment' },
    { id: 40, name: 'Environmental Services' },
    { id: 41, name: 'Events Services' },
    { id: 42, name: 'Executive Office' },
    { id: 43, name: 'Facilities Services' },
    { id: 44, name: 'Farming' },
    { id: 45, name: 'Financial Services' },
    { id: 46, name: 'Fine Art' },
    { id: 47, name: 'Fishery' },
    { id: 48, name: 'Food & Beverages' },
    { id: 49, name: 'Food Production' },
    { id: 50, name: 'Fund-Raising' },
    { id: 51, name: 'Furniture' },
    { id: 52, name: 'Gambling & Casinos' },
    { id: 53, name: 'Glass Ceramics & Concrete' },
    { id: 54, name: 'Government Administration' },
    { id: 55, name: 'Government Relations' },
    { id: 56, name: 'Graphic Design' },
    { id: 57, name: 'Health Care' },
    { id: 58, name: 'Health Wellness and Fitness' },
    { id: 59, name: 'Higher Education' },
    { id: 60, name: 'Hospital & Health Care' },
    { id: 61, name: 'Hospitality' },
    { id: 62, name: 'Human Resources' },
    { id: 63, name: 'Import and Export' },
    { id: 64, name: 'Individual & Family Services' },
    { id: 65, name: 'Industrial Automation' },
    { id: 66, name: 'Information Services' },
    { id: 67, name: 'Information Technology and Services' },
    { id: 68, name: 'Insurance' },
    { id: 69, name: 'International Affairs' },
    { id: 70, name: 'International Trade and Development' },
    { id: 71, name: 'Internet' },
    { id: 72, name: 'Investment Banking' },
    { id: 73, name: 'Investment Management' },
    { id: 74, name: 'Judiciary' },
    { id: 75, name: 'Law Enforcement' },
    { id: 76, name: 'Law Practice' },
    { id: 77, name: 'Legal Services' },
    { id: 78, name: 'Legislative Office' },
    { id: 79, name: 'Leisure Travel & Tourism' },
    { id: 80, name: 'Libraries' },
    { id: 81, name: 'Logistics and Supply Chain' },
    { id: 82, name: 'Luxury Goods & Jewelry' },
    { id: 83, name: 'Machinery' },
    { id: 84, name: 'Management Consulting' },
    { id: 85, name: 'Maritime' },
    { id: 86, name: 'Market Research' },
    { id: 87, name: 'Marketing and Advertising' },
    { id: 88, name: 'Mechanical or Industrial Engineering' },
    { id: 89, name: 'Media Production' },
    { id: 90, name: 'Medical Devices' },
    { id: 91, name: 'Medical Practice' },
    { id: 92, name: 'Mental Health Care' },
    { id: 93, name: 'Military' },
    { id: 94, name: 'Mining & Metals' },
    { id: 95, name: 'Motion Pictures and Film' },
    { id: 96, name: 'Museums and Institutions' },
    { id: 97, name: 'Music' },
    { id: 98, name: 'Nanotechnology' },
    { id: 99, name: 'Nonprofit Organization Management' },
    { id: 100, name: 'Oil & Energy' },
    { id: 101, name: 'Online Media' },
    { id: 102, name: 'Outsourcing/Offshoring' },
    { id: 103, name: 'Package/Freight Delivery' },
    { id: 104, name: 'Packaging and Containers' },
    { id: 105, name: 'Paper & Forest Products' },
    { id: 106, name: 'Performing Arts' },
    { id: 107, name: 'Pharmaceuticals' },
    { id: 108, name: 'Philanthropy' },
    { id: 109, name: 'Photography' },
    { id: 110, name: 'Plastics' },
    { id: 111, name: 'Political Organization' },
    { id: 112, name: 'Primary/Secondary Education' },
    { id: 113, name: 'Printing' },
    { id: 114, name: 'Professional Training & Coaching' },
    { id: 115, name: 'Program Development' },
    { id: 116, name: 'Public Policy' },
    { id: 117, name: 'Public Relations and Communications' },
    { id: 118, name: 'Public Safety' },
    { id: 119, name: 'Publishing' },
    { id: 120, name: 'Railroad Manufacture' },
    { id: 121, name: 'Ranching' },
    { id: 122, name: 'Real Estate' },
    { id: 123, name: 'Recreational Facilities and Services' },
    { id: 124, name: 'Religious Institutions' },
    { id: 125, name: 'Renewables & Environment' },
    { id: 126, name: 'Research' },
    { id: 127, name: 'Restaurants' },
    { id: 128, name: 'Retail' },
    { id: 129, name: 'Security and Investigations' },
    { id: 130, name: 'Semiconductors' },
    { id: 131, name: 'Shipbuilding' },
    { id: 132, name: 'Software' },
    { id: 133, name: 'Sporting Goods' },
    { id: 134, name: 'Sports' },
    { id: 135, name: 'Staffing and Recruiting' },
    { id: 136, name: 'Supermarkets' },
    { id: 137, name: 'Telecommunications' },
    { id: 138, name: 'Textiles' },
    { id: 139, name: 'Think Tanks' },
    { id: 140, name: 'Tobacco' },
    { id: 141, name: 'Training' },
    { id: 142, name: 'Translation and Localization' },
    { id: 143, name: 'Transportation/Trucking/Railroad' },
    { id: 144, name: 'Utilities' },
    { id: 145, name: 'Venture Capital & Private Equity' },
    { id: 146, name: 'Veterinary' },
    { id: 147, name: 'Warehousing' },
    { id: 148, name: 'Wholesale' },
    { id: 149, name: 'Wine and Spirits' },
    { id: 150, name: 'Wireless' },
    { id: 151, name: 'Writing and Editing' },
];

export const mockPeerGroups = {
    peerGroups: [
        {
            id: 1,
            name: 'Kornferry',
        },
        {
            id: 2,
            name: 'Apple',
        },
        {
            id: 3,
            name: 'Facebook',
        },
        {
            id: 4,
            name: 'Google',
        },
        {
            id: 5,
            name: 'IBM',
        },
    ],
};
