/* eslint-disable sonarjs/no-duplicate-string */
export const postMockResponse = [
    {
        LearningAssetID: '11',
        LearningAssetName: 'Adapting to Constant Change',
        LearningAssetDescription:
            'The business landscape in which we operate is more complex, ambiguous, and at times volatile than ever before, all of which can lead to distraction, stress, anxiety, and disengagement. To be successful in this environment, leaders and the people they lead must be highly adaptable, able to perform at high levels in the midst of this constant change and uncertainty. In this module participants will be introduced to a set of techniques for building their own adaptability. Through lively conversations, videos, and real-life practice, they will begin to build the skills and confidence to enhance their ability to perform more effectively under conditions of continuous change and uncertainty.',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~3~~|INSTRUCTOR_LED~4~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263366',
        JobSubcategoryCde: 'BEH103',
        JobSubCategoryName: 'إدارة الغموض',
    },
    {
        LearningAssetID: '23',
        LearningAssetName: 'Making Collaborative Decisions',
        LearningAssetDescription:
            'This course provides an easy-to-use framework and a set of valuable techniques for conducting collaborative, productive discussions of any type. Via videos, lively conversations, and real-life practice, participants will build the skills and confidence required to converse comfortably with people up, down, and across the organization.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~4~~|VIRTUAL_INSTRUCTOR_LED~3~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263370',
        JobSubcategoryCde: 'BEH108',
        JobSubCategoryName: 'إدارة الأمور المعقدة',
    },
    {
        LearningAssetID: '34',
        LearningAssetName: 'Leading Complex Decisions',
        LearningAssetDescription:
            'Managers equipped with a process, strategies, and tools for improving the quality and speed of making complex decisions—and for ensuring that those decisions stick.',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~8~~|INSTRUCTOR_LED~8~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263370',
        JobSubcategoryCde: 'BEH108',
        JobSubCategoryName: 'إدارة الأمور المعقدة',
    },

    {
        LearningAssetID: '9',
        LearningAssetName: 'Building Trust Under Pressure: The Basic Principles',
        LearningAssetDescription: 'Leaders with solid foundational leadership habits for building productivity and strong working relationships.​',
        CourseID: 'f3ac7948-2e22-4a69-a4b2-5126be74d5ec',
        ModalityDurationDirectURLImage:
            'VIRTUAL_INSTRUCTOR_LED~2~~|INSTRUCTOR_LED~5~~|E_LEARNING~0~https://learn.kornferry.com/learn/learning-path/af-building-trust-under-pressure~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/q_100,a_exif,c_crop,x_0,y_146,w_4896,h_2357/a_exif,c_fit,w_800,h_385/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/vrj5v70dagu2-GettyImages-1072980098.jpg',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263372',
        JobSubcategoryCde: 'BEH110',
        JobSubCategoryName: 'الشجاعة',
    },
    {
        LearningAssetID: '25',
        LearningAssetName: 'Influencing Outcomes Through Others',
        LearningAssetDescription:
            'Every day, leaders shape the future by offering proposals, selling ideas, and encouraging others to take action. Effective leaders know that the best way to influence outcomes is to actively engage and collaborate with others through dialogue. Communicating a clear, concise, compelling message is essential given the ever-expanding volume of information and ever-shrinking human attention span. Laser-like communication focuses on the listener with genuine commitment to two-way dialogue. This module will help participants prepare, deliver, and discuss their ideas, proposals, and requests to support business outcomes.​',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~3~~|INSTRUCTOR_LED~4~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263372',
        JobSubcategoryCde: 'BEH110',
        JobSubCategoryName: 'الشجاعة',
    },
    {
        LearningAssetID: '44',
        LearningAssetName: 'Resolving Conflicts with Your Peers',
        LearningAssetDescription:
            'When individuals work together, differences in opinions, work styles, and personalities will occur. These differences often lead to conflict. Team conflict can be constructive—helping to unleash creativity and innovative thinking, Promoting growth and learning, and building team unity. When left unchecked, however, conflict can become a highly destructive force—eroding trust, undermining team pride and cohesiveness, and causing serious performance shortfalls.',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~2~~|INSTRUCTOR_LED~4~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263372',
        JobSubcategoryCde: 'BEH110',
        JobSubCategoryName: 'الشجاعة',
    },
    {
        LearningAssetID: '141',
        LearningAssetName: 'Managing Critical Relationships',
        LearningAssetDescription:
            'Managing Critical Relationships provides the learner with the skills and tools necessary to master the intricacies of relationship management in the contemporary work context. It begins with understanding the implications for those teams and individuals that cooperate and those that don’t. It does so with a particular focus on identifying different types of stakeholders in critical relationships. Then, based on that identification, the learner can analyze their stakeholders to determine their level of support and their most important issues with an eye toward creating an engagement plan customized to each stakeholder’s needs.',
        CourseID: '4c180429-ea60-4617-85c5-fa95c9bcdf87',
        ModalityDurationDirectURLImage:
            'VIRTUAL_INSTRUCTOR_LED~21~~|INSTRUCTOR_LED~21~~|E_LEARNING~21~https://learn.kornferry.com/learn/course/managing-critical-relationships~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/mz098pvejfot-GettyImages-1073160322.jpg',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263372',
        JobSubcategoryCde: 'BEH110',
        JobSubCategoryName: 'الشجاعة',
    },
    {
        LearningAssetID: '139',
        LearningAssetName: 'Building Effective TeamCollection',
        LearningAssetDescription:
            'Building Effective TeamCollection focuses on how to implement practices for leading highly effective teams in unstable and often distributed environments. Participants will learn how to build and guide diverse teams that can navigate the impacts of external and internal forces and how to form, coach, and lead teams that are resilient and responsive to complex work and volatile contexts.',
        CourseID: '8f950695-4591-46c9-ab55-0b84b3b30937',
        ModalityDurationDirectURLImage:
            'VIRTUAL_INSTRUCTOR_LED~21~~|INSTRUCTOR_LED~21~~|E_LEARNING~21~https://learn.kornferry.com/learn/course/adx-gvb-building-effective-teams~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/m2buf9wi8ndl-GettyImages-1072011524.jpg',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263375',
        JobSubcategoryCde: 'BEH113',
        JobSubCategoryName: 'تطوير المواهب',
    },
    {
        LearningAssetID: '9',
        LearningAssetName: 'Building Trust Under Pressure: The Basic Principles',
        LearningAssetDescription: 'Leaders with solid foundational leadership habits for building productivity and strong working relationships.​',
        CourseID: 'f3ac7948-2e22-4a69-a4b2-5126be74d5ec',
        ModalityDurationDirectURLImage:
            'VIRTUAL_INSTRUCTOR_LED~2~~|INSTRUCTOR_LED~5~~|E_LEARNING~0~https://learn.kornferry.com/learn/learning-path/af-building-trust-under-pressure~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/q_100,a_exif,c_crop,x_0,y_146,w_4896,h_2357/a_exif,c_fit,w_800,h_385/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/vrj5v70dagu2-GettyImages-1072980098.jpg',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263382',
        JobSubcategoryCde: 'BEH120',
        JobSubCategoryName: 'إدراك العلاقات الشخصية',
    },
    {
        LearningAssetID: '23',
        LearningAssetName: 'Making Collaborative Decisions',
        LearningAssetDescription:
            'This course provides an easy-to-use framework and a set of valuable techniques for conducting collaborative, productive discussions of any type. Via videos, lively conversations, and real-life practice, participants will build the skills and confidence required to converse comfortably with people up, down, and across the organization.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~4~~|VIRTUAL_INSTRUCTOR_LED~3~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263382',
        JobSubcategoryCde: 'BEH120',
        JobSubCategoryName: 'إدراك العلاقات الشخصية',
    },
    {
        LearningAssetID: '25',
        LearningAssetName: 'Influencing Outcomes Through Others',
        LearningAssetDescription:
            'Every day, leaders shape the future by offering proposals, selling ideas, and encouraging others to take action. Effective leaders know that the best way to influence outcomes is to actively engage and collaborate with others through dialogue. Communicating a clear, concise, compelling message is essential given the ever-expanding volume of information and ever-shrinking human attention span. Laser-like communication focuses on the listener with genuine commitment to two-way dialogue. This module will help participants prepare, deliver, and discuss their ideas, proposals, and requests to support business outcomes.​',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~3~~|INSTRUCTOR_LED~4~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263382',
        JobSubcategoryCde: 'BEH120',
        JobSubCategoryName: 'إدراك العلاقات الشخصية',
    },
    {
        LearningAssetID: '44',
        LearningAssetName: 'Resolving Conflicts with Your Peers',
        LearningAssetDescription:
            'When individuals work together, differences in opinions, work styles, and personalities will occur. These differences often lead to conflict. Team conflict can be constructive—helping to unleash creativity and innovative thinking, Promoting growth and learning, and building team unity. When left unchecked, however, conflict can become a highly destructive force—eroding trust, undermining team pride and cohesiveness, and causing serious performance shortfalls.',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~2~~|INSTRUCTOR_LED~4~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263382',
        JobSubcategoryCde: 'BEH120',
        JobSubCategoryName: 'إدراك العلاقات الشخصية',
    },
    {
        LearningAssetID: '141',
        LearningAssetName: 'Managing Critical Relationships',
        LearningAssetDescription:
            'Managing Critical Relationships provides the learner with the skills and tools necessary to master the intricacies of relationship management in the contemporary work context. It begins with understanding the implications for those teams and individuals that cooperate and those that don’t. It does so with a particular focus on identifying different types of stakeholders in critical relationships. Then, based on that identification, the learner can analyze their stakeholders to determine their level of support and their most important issues with an eye toward creating an engagement plan customized to each stakeholder’s needs.',
        CourseID: '4c180429-ea60-4617-85c5-fa95c9bcdf87',
        ModalityDurationDirectURLImage:
            'VIRTUAL_INSTRUCTOR_LED~21~~|INSTRUCTOR_LED~21~~|E_LEARNING~21~https://learn.kornferry.com/learn/course/managing-critical-relationships~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/mz098pvejfot-GettyImages-1073160322.jpg',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263382',
        JobSubcategoryCde: 'BEH120',
        JobSubCategoryName: 'إدراك العلاقات الشخصية',
    },
    {
        LearningAssetID: '25',
        LearningAssetName: 'Influencing Outcomes Through Others',
        LearningAssetDescription:
            'Every day, leaders shape the future by offering proposals, selling ideas, and encouraging others to take action. Effective leaders know that the best way to influence outcomes is to actively engage and collaborate with others through dialogue. Communicating a clear, concise, compelling message is essential given the ever-expanding volume of information and ever-shrinking human attention span. Laser-like communication focuses on the listener with genuine commitment to two-way dialogue. This module will help participants prepare, deliver, and discuss their ideas, proposals, and requests to support business outcomes.​',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~3~~|INSTRUCTOR_LED~4~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263386',
        JobSubcategoryCde: 'BEH124',
        JobSubCategoryName: 'الإقناع',
    },
    {
        LearningAssetID: '110',
        LearningAssetName: 'Project Management for Non-Project Managers',
        LearningAssetDescription:
            'Master the skill to become a good project manager with this highly-facilitated one-day workshop. In this workshop we will teach you a simple 4-step model that will help you maximize project success.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~7~~|VIRTUAL_INSTRUCTOR_LED~7~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263387',
        JobSubcategoryCde: 'BEH125',
        JobSubCategoryName: 'التخطيط والمواكبة',
    },
    {
        LearningAssetID: '111',
        LearningAssetName: 'Managing Projects',
        LearningAssetDescription:
            'Get a solid understanding of project management methods with this comprehensive introductory course. Gain practical experience in proven project management techniques and discover a wealth of valuable, flexible tools that you can use immediately to ensure the success of any project in any type of organization.',
        CourseID: '516f56cd-bb00-41b6-8eb0-4702d1e0b7aa',
        ModalityDurationDirectURLImage:
            'VIRTUAL_INSTRUCTOR_LED~22~~|INSTRUCTOR_LED~22~~|E_LEARNING~22~https://learn.kornferry.com/learn/course/pmc-cpm-managing-projects-lift-and-shift~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/r91boh00wd7w-GettyImages-915102480.jpg',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263387',
        JobSubcategoryCde: 'BEH125',
        JobSubCategoryName: 'التخطيط والمواكبة',
    },
    {
        LearningAssetID: '110',
        LearningAssetName: 'Project Management for Non-Project Managers',
        LearningAssetDescription:
            'Master the skill to become a good project manager with this highly-facilitated one-day workshop. In this workshop we will teach you a simple 4-step model that will help you maximize project success.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~7~~|VIRTUAL_INSTRUCTOR_LED~7~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263390',
        JobSubcategoryCde: 'BEH128',
        JobSubCategoryName: ' تحقيق النتائج',
    },
    {
        LearningAssetID: '117',
        LearningAssetName: 'Project Leadership, Management and Communications',
        LearningAssetDescription:
            'Project Leadership, Management and Communications is an interactive course designed to provide a solid foundation in key leadership competencies and to afford you the opportunity for a truly transformational leadership experience. As a participant, you will complete a self-assessment of your leadership skills, then master the basics of these leadership competencies: setting direction, aligning people, motivating and inspiring, leading teams, communicating, building relationships, facilitating ethical conduct, negotiating and leading change.',
        CourseID: '03530e56-cdf2-4395-8027-50ff5f9b5975',
        ModalityDurationDirectURLImage:
            'VIRTUAL_INSTRUCTOR_LED~22~~|INSTRUCTOR_LED~22~~|E_LEARNING~22~https://learn.kornferry.com/learn/course/pmc-dbq-project-leadership-management-and-communications-lift-and-shift~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/grmqwyo1fb61-GettyImages-953533880.jpg',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263390',
        JobSubcategoryCde: 'BEH128',
        JobSubCategoryName: ' تحقيق النتائج',
    },
    {
        LearningAssetID: '11',
        LearningAssetName: 'Adapting to Constant Change',
        LearningAssetDescription:
            'The business landscape in which we operate is more complex, ambiguous, and at times volatile than ever before, all of which can lead to distraction, stress, anxiety, and disengagement. To be successful in this environment, leaders and the people they lead must be highly adaptable, able to perform at high levels in the midst of this constant change and uncertainty. In this module participants will be introduced to a set of techniques for building their own adaptability. Through lively conversations, videos, and real-life practice, they will begin to build the skills and confidence to enhance their ability to perform more effectively under conditions of continuous change and uncertainty.',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~3~~|INSTRUCTOR_LED~4~~',
        JobSectionID: '1141',
        JobSectionCode: 'BEHAVIORAL_SKILLS',
        JobSectionname: 'Behavioral Competencies ',
        JobCategoryID: '15735',
        JobCategoryName: 'CLM Test Company 1 Behavior',
        JobSubcategoryID: '263392',
        JobSubcategoryCde: 'BEH130',
        JobSubCategoryName: 'تطوير الذات',
    },
    {
        LearningAssetID: '98',
        LearningAssetName: 'Fundamentals of Lean and Agile',
        LearningAssetDescription:
            'Fundamentals of Lean and Agile provides a foundational exploration of what it means to be Lean and Agile. In this course, attendees not only learn the value and basics of Lean and Agile execution – they also learn many of the necessary “other” elements of any successful Lean and Agile environment. Curriculum includes overviews on Lean and Agile philosophy, myths and how they work together, overviews on both iterative and continuous delivery methods, overviews on Scrum and Kanban and overviews on how Lean and Agile work is generated, valued, sized and represented; all of which contribute to a clear understanding of the Lean and Agile universe in preparation for more advanced concepts and techniques.',
        CourseID: 'd0586d3a-3243-4a0d-8234-b7cd44dcde7c',
        ModalityDurationDirectURLImage:
            'INSTRUCTOR_LED~7~~|VIRTUAL_INSTRUCTOR_LED~7~~|E_LEARNING~7~https://learn.kornferry.com/learn/course/agx-gtb-fundamentals-of-lean-and-agile-lift-and-shift~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/txoypbk28yas-GettyImages-1072011398.jpg',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15780',
        JobCategoryName: 'GENERIC KNOWLEDGE SKILLS & ABILITIES',
        JobSubcategoryID: '263693',
        JobSubcategoryCde: 'KSA016',
        JobSubCategoryName: 'Project Management EDITED IN CL',
    },
    {
        LearningAssetID: '104',
        LearningAssetName: 'Agile Projects: Keys to Getting Started',
        LearningAssetDescription:
            'Agile Projects: Keys to Getting Started gives participants the opportunity to select a project for agile development; determine the readiness of the organization, team, customer and project manager; and work through the life cycle of an Agile project.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~22~~|VIRTUAL_INSTRUCTOR_LED~22~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15780',
        JobCategoryName: 'GENERIC KNOWLEDGE SKILLS & ABILITIES',
        JobSubcategoryID: '263693',
        JobSubcategoryCde: 'KSA016',
        JobSubCategoryName: 'Project Management EDITED IN CL',
    },
    {
        LearningAssetID: '110',
        LearningAssetName: 'Project Management for Non-Project Managers',
        LearningAssetDescription:
            'Master the skill to become a good project manager with this highly-facilitated one-day workshop. In this workshop we will teach you a simple 4-step model that will help you maximize project success.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~7~~|VIRTUAL_INSTRUCTOR_LED~7~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15780',
        JobCategoryName: 'GENERIC KNOWLEDGE SKILLS & ABILITIES',
        JobSubcategoryID: '263693',
        JobSubcategoryCde: 'KSA016',
        JobSubCategoryName: 'Project Management EDITED IN CL',
    },
    {
        LearningAssetID: '111',
        LearningAssetName: 'Managing Projects',
        LearningAssetDescription:
            'Get a solid understanding of project management methods with this comprehensive introductory course. Gain practical experience in proven project management techniques and discover a wealth of valuable, flexible tools that you can use immediately to ensure the success of any project in any type of organization.',
        CourseID: '516f56cd-bb00-41b6-8eb0-4702d1e0b7aa',
        ModalityDurationDirectURLImage:
            'VIRTUAL_INSTRUCTOR_LED~22~~|INSTRUCTOR_LED~22~~|E_LEARNING~22~https://learn.kornferry.com/learn/course/pmc-cpm-managing-projects-lift-and-shift~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/r91boh00wd7w-GettyImages-915102480.jpg',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15780',
        JobCategoryName: 'GENERIC KNOWLEDGE SKILLS & ABILITIES',
        JobSubcategoryID: '263693',
        JobSubcategoryCde: 'KSA016',
        JobSubCategoryName: 'Project Management EDITED IN CL',
    },
    {
        LearningAssetID: '114',
        LearningAssetName: 'Risk Management',
        LearningAssetDescription:
            'In this Risk Management course, you’ll work through the proactive approach to threat and opportunity—based on a clear understanding of the powerful nature of both qualitative and quantitative approaches to risk management.',
        CourseID: '63e17872-6c88-4e15-8241-46e9bdb7f515',
        ModalityDurationDirectURLImage:
            'E_LEARNING~22~https://learn.kornferry.com/learn/course/pmc-ctl-risk-management-lift-and-shift~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/in5345t58lxm-gettyimages-905819004-170667a.jpg|INSTRUCTOR_LED~22~~|VIRTUAL_INSTRUCTOR_LED~22~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15781',
        JobCategoryName: 'SHARED / CROSS FUNCTION KNOWLEDGE SKILLS & ABILITIES',
        JobSubcategoryID: '263712',
        JobSubcategoryCde: 'KSA035',
        JobSubCategoryName: 'Risk Management',
    },
    {
        LearningAssetID: '131',
        LearningAssetName: 'Critical Thinking and Problem Solving',
        LearningAssetDescription:
            'This course presents a structured approach for tackling problems, opportunities and decisions that will ultimately help you get better results—whether you are innovating, managing crises or planning for the future. The course addresses the five types of critical thinking needed in business environments: strategic thinking, tactical thinking, analytical thinking, innovative thinking and implicative thinking.',
        ModalityDurationDirectURLImage: 'VIRTUAL_INSTRUCTOR_LED~22~~|INSTRUCTOR_LED~22~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15781',
        JobCategoryName: 'SHARED / CROSS FUNCTION KNOWLEDGE SKILLS & ABILITIES',
        JobSubcategoryID: '263712',
        JobSubcategoryCde: 'KSA035',
        JobSubCategoryName: 'Risk Management',
    },
    {
        LearningAssetID: '98',
        LearningAssetName: 'Fundamentals of Lean and Agile',
        LearningAssetDescription:
            'Fundamentals of Lean and Agile provides a foundational exploration of what it means to be Lean and Agile. In this course, attendees not only learn the value and basics of Lean and Agile execution – they also learn many of the necessary “other” elements of any successful Lean and Agile environment. Curriculum includes overviews on Lean and Agile philosophy, myths and how they work together, overviews on both iterative and continuous delivery methods, overviews on Scrum and Kanban and overviews on how Lean and Agile work is generated, valued, sized and represented; all of which contribute to a clear understanding of the Lean and Agile universe in preparation for more advanced concepts and techniques.',
        CourseID: 'd0586d3a-3243-4a0d-8234-b7cd44dcde7c',
        ModalityDurationDirectURLImage:
            'INSTRUCTOR_LED~7~~|VIRTUAL_INSTRUCTOR_LED~7~~|E_LEARNING~7~https://learn.kornferry.com/learn/course/agx-gtb-fundamentals-of-lean-and-agile-lift-and-shift~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/txoypbk28yas-GettyImages-1072011398.jpg',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15782',
        JobCategoryName: 'Administrative',
        JobSubcategoryID: '263690',
        JobSubcategoryCde: 'KSA013',
        JobSubCategoryName: 'B21.04 CL Planning and Organizing',
    },
    {
        LearningAssetID: '110',
        LearningAssetName: 'Project Management for Non-Project Managers',
        LearningAssetDescription:
            'Master the skill to become a good project manager with this highly-facilitated one-day workshop. In this workshop we will teach you a simple 4-step model that will help you maximize project success.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~7~~|VIRTUAL_INSTRUCTOR_LED~7~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15782',
        JobCategoryName: 'Administrative',
        JobSubcategoryID: '263690',
        JobSubcategoryCde: 'KSA013',
        JobSubCategoryName: 'B21.04 CL Planning and Organizing',
    },
    {
        LearningAssetID: '1',
        LearningAssetName: 'Professional Selling Skills',
        LearningAssetDescription:
            'Professional Selling Skills® reflects the skills used by world-class sales professionals to help customers succeed, including understanding customer needs and consistently developing solutions that deliver results. A research-based program, Professional Selling Skills® teaches customer interaction skills that enable participants to lead mutually beneficial sales conversations with customers—even those who are indifferent or express concerns.',
        CourseID: 'b497b7ff-6904-4335-9e88-362a7b34a400',
        ModalityDurationDirectURLImage:
            'INSTRUCTOR_LED~16~~|VIRTUAL_INSTRUCTOR_LED~16~~|E_LEARNING~3~https://learn.kornferry.com/learn/learning-path/professional-selling-skills~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/q_100,a_exif,c_crop,x_0,y_0,w_299,h_144/a_exif,c_fit,w_800,h_385/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/082n8qg6n4zt--PSS_HUB_Image.png',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263800',
        JobSubcategoryCde: 'KSA124',
        JobSubCategoryName: 'Effectively Presents Solutions',
    },
    {
        LearningAssetID: '2',
        LearningAssetName: 'SPIN Selling Conversations',
        LearningAssetDescription:
            'SPIN® Selling Conversations teaches sales professionals to use specific behaviors and skills to have deeper, more insightful conversations with customers as they move toward a buying decision. Participants learn how to listen for customer need statements that signal when is the best time to discuss a solution. They learn how to use SPIN Questions as powerful tools to help a customer explore problems, the impacts of not addressing them, and the payoffs of finding the right solution.',
        CourseID: '628a04f3-1e24-48ae-9dd3-e4c614d35cfc',
        ModalityDurationDirectURLImage:
            'E_LEARNING~3~https://learn.kornferry.com/learn/course/spin-selling-conversations-full-digital~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/gzj62n0crsdv-SSwp_HubImage.png|VIRTUAL_INSTRUCTOR_LED~8~~|INSTRUCTOR_LED~8~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263800',
        JobSubcategoryCde: 'KSA124',
        JobSubCategoryName: 'Effectively Presents Solutions',
    },
    {
        LearningAssetID: '3',
        LearningAssetName: 'Strategic Selling with Perspective',
        LearningAssetDescription:
            'For more than 40 years, Miller Heiman Group’s Strategic Selling® has helped sellers win more deals faster. With the new addition of Perspective and Scout by Miller Heiman Group, Strategic Selling with Perspective® is the strongest selling process available. In a world of rapidly changing buyer expectations, your selling teams need to provide insight and value through Perspective in a strategic way. Create a path for your strategy to fuel action in complex sales cycles.',
        CourseID: '81d653bd-695f-414c-9345-61e01023617e',
        ModalityDurationDirectURLImage:
            'INSTRUCTOR_LED~16~~|VIRTUAL_INSTRUCTOR_LED~16~~|E_LEARNING~5~https://learn.kornferry.com/learn/course/strategic-selling-with-perspective~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/gzj62n0crsdv-SSwp_HubImage.png',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263800',
        JobSubcategoryCde: 'KSA124',
        JobSubCategoryName: 'Effectively Presents Solutions',
    },
    {
        LearningAssetID: '4',
        LearningAssetName: 'Conceptual Selling with Perspective',
        LearningAssetDescription:
            'Every interaction with a customer is too important to leave to chance. Conceptual Selling® with Perspective helps salespeople better prepare for their time with customers. Understanding your customer’s perspective is a key ingredient to moving deals and results in more purposeful meetings and win-win outcomes. This program provides the simple, repeatable structure that should be considered essential for anyone who interacts with customers.',
        CourseID: '1cc61662-e54d-4ef6-bac3-933dd1cc56f6',
        ModalityDurationDirectURLImage:
            'E_LEARNING~3~https://learn.kornferry.com/learn/course/conceptual-selling-with-perspective~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/d8tka0nqf6f1-CS_HubImage.png|VIRTUAL_INSTRUCTOR_LED~16~~|INSTRUCTOR_LED~16~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263800',
        JobSubcategoryCde: 'KSA124',
        JobSubCategoryName: 'Effectively Presents Solutions',
    },
    {
        LearningAssetID: '3',
        LearningAssetName: 'Strategic Selling with Perspective',
        LearningAssetDescription:
            'For more than 40 years, Miller Heiman Group’s Strategic Selling® has helped sellers win more deals faster. With the new addition of Perspective and Scout by Miller Heiman Group, Strategic Selling with Perspective® is the strongest selling process available. In a world of rapidly changing buyer expectations, your selling teams need to provide insight and value through Perspective in a strategic way. Create a path for your strategy to fuel action in complex sales cycles.',
        CourseID: '81d653bd-695f-414c-9345-61e01023617e',
        ModalityDurationDirectURLImage:
            'INSTRUCTOR_LED~16~~|VIRTUAL_INSTRUCTOR_LED~16~~|E_LEARNING~5~https://learn.kornferry.com/learn/course/strategic-selling-with-perspective~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/gzj62n0crsdv-SSwp_HubImage.png',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263808',
        JobSubcategoryCde: 'KSA132',
        JobSubCategoryName: 'Negotiates Strategically/Tactically',
    },
    {
        LearningAssetID: '5',
        LearningAssetName: 'Professional Sales Negotiations',
        LearningAssetDescription:
            'Professional Sales Negotiations™ is built on recent global research which identified the critical success factors associated with negotiation success today and into the future. A two-day program, Professional Sales Negotiations™ focuses on three key areas: Sales Negotiations Defined, Preparation, and Leading a Negotiation. Throughout the program, participants focus on planning for their own client negotiations, brainstorming options with their peers, and practicing negotiation strategies. Importantly, participants work with complex negotiating situations in class, allowing them to succeed in the field − in not only similar scenarios− but also “in the moment” or less complex scenarios.',
        MessageToDisplay:
            'This course is delivered as Instructor-Led Training or Virtual Instructor-Led Training only. Please contact your manager to discuss next steps and attend this program.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~16~~|VIRTUAL_INSTRUCTOR_LED~16~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263808',
        JobSubcategoryCde: 'KSA132',
        JobSubCategoryName: 'Negotiates Strategically/Tactically',
    },
    {
        LearningAssetID: '3',
        LearningAssetName: 'Strategic Selling with Perspective',
        LearningAssetDescription:
            'For more than 40 years, Miller Heiman Group’s Strategic Selling® has helped sellers win more deals faster. With the new addition of Perspective and Scout by Miller Heiman Group, Strategic Selling with Perspective® is the strongest selling process available. In a world of rapidly changing buyer expectations, your selling teams need to provide insight and value through Perspective in a strategic way. Create a path for your strategy to fuel action in complex sales cycles.',
        CourseID: '81d653bd-695f-414c-9345-61e01023617e',
        ModalityDurationDirectURLImage:
            'INSTRUCTOR_LED~16~~|VIRTUAL_INSTRUCTOR_LED~16~~|E_LEARNING~5~https://learn.kornferry.com/learn/course/strategic-selling-with-perspective~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/gzj62n0crsdv-SSwp_HubImage.png',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263816',
        JobSubcategoryCde: 'KSA140',
        JobSubCategoryName: 'Understands Issues/Motivations',
    },
    {
        LearningAssetID: '4',
        LearningAssetName: 'Conceptual Selling with Perspective',
        LearningAssetDescription:
            'Every interaction with a customer is too important to leave to chance. Conceptual Selling® with Perspective helps salespeople better prepare for their time with customers. Understanding your customer’s perspective is a key ingredient to moving deals and results in more purposeful meetings and win-win outcomes. This program provides the simple, repeatable structure that should be considered essential for anyone who interacts with customers.',
        CourseID: '1cc61662-e54d-4ef6-bac3-933dd1cc56f6',
        ModalityDurationDirectURLImage:
            'E_LEARNING~3~https://learn.kornferry.com/learn/course/conceptual-selling-with-perspective~https://d36ai2hkxl16us.cloudfront.net/thoughtindustries/image/upload/a_exif,c_fit,w_300/v1/course-uploads/e1e4c2d6-3c2b-4f86-87b2-7e6b35cd26f8/d8tka0nqf6f1-CS_HubImage.png|VIRTUAL_INSTRUCTOR_LED~16~~|INSTRUCTOR_LED~16~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263816',
        JobSubcategoryCde: 'KSA140',
        JobSubCategoryName: 'Understands Issues/Motivations',
    },
    {
        LearningAssetID: '5',
        LearningAssetName: 'Professional Sales Negotiations',
        LearningAssetDescription:
            'Professional Sales Negotiations™ is built on recent global research which identified the critical success factors associated with negotiation success today and into the future. A two-day program, Professional Sales Negotiations™ focuses on three key areas: Sales Negotiations Defined, Preparation, and Leading a Negotiation. Throughout the program, participants focus on planning for their own client negotiations, brainstorming options with their peers, and practicing negotiation strategies. Importantly, participants work with complex negotiating situations in class, allowing them to succeed in the field − in not only similar scenarios− but also “in the moment” or less complex scenarios.',
        MessageToDisplay:
            'This course is delivered as Instructor-Led Training or Virtual Instructor-Led Training only. Please contact your manager to discuss next steps and attend this program.',
        ModalityDurationDirectURLImage: 'INSTRUCTOR_LED~16~~|VIRTUAL_INSTRUCTOR_LED~16~~',
        JobSectionID: '1143',
        JobSectionCode: 'TECHNICAL_SKILLS',
        JobSectionname: 'Technical Competencies',
        JobCategoryID: '15797',
        JobCategoryName: 'Sales',
        JobSubcategoryID: '263816',
        JobSubcategoryCde: 'KSA140',
        JobSubCategoryName: 'Understands Issues/Motivations',
    },
];
