import { AddNewSubcategories, NewModelDBResponse } from './responsibilities.interface';

export const ModelQuery = {
    preferredLocale: 'en',
    preferredClientId: 23139,
    modelVersion: 1.0,
    outputType: 'RESPONSIBILITY',
    locale: 'en',
    userId: 26087,
    loggedInUserClientId: 23139,
};

export const OldModelDBResponseMock = [
    {
        JobCategoryID: 99903,
        JobCategoryName:
            '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors|02.17.2021 smoke CL added subfunction edited by me',
        JobCategoryDescription: 'Custom JobSubFamily',
    },
    {
        JobCategoryID: 94682,
        JobCategoryName: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors|subfunc1',
        JobCategoryDescription: 'Custom JobSubFamily',
    },
    {
        JobCategoryID: 99901,
        JobCategoryName: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors|subfunc2',
        JobCategoryDescription: 'Custom JobSubFamily',
    },
    {
        JobCategoryID: 158608,
        JobCategoryName: '02.19.2021 CL weekly smoke added function|02.19.2021 CL weekly smoke added subfunc 1',
        JobCategoryDescription: 'Custom JobSubFamily',
    },
    {
        JobCategoryID: 158609,
        JobCategoryName: '02.19.2021 CL weekly smoke added function|02.19.2021 CL weekly smoke added subfunc 2',
        JobCategoryDescription: 'Custom JobSubFamily',
    },
];

export const OldModelAPIResponse = {
    models: {
        categories: [
            {
                id: 99903,
                name: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors|02.17.2021 smoke CL added subfunction edited by me',
                description: 'Custom JobSubFamily',
            },
            {
                id: 94682,
                name: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors|subfunc1',
                description: 'Custom JobSubFamily',
            },
            {
                id: 99901,
                name: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors|subfunc2',
                description: 'Custom JobSubFamily',
            },
            { id: 158608, name: '02.19.2021 CL weekly smoke added function|02.19.2021 CL weekly smoke added subfunc 1', description: 'Custom JobSubFamily' },
            { id: 158609, name: '02.19.2021 CL weekly smoke added function|02.19.2021 CL weekly smoke added subfunc 2', description: 'Custom JobSubFamily' },
        ],
    },
    status: 'MODIFIED',
};

export const GetResponsibilityModelQuery = {
    preferredLocale: 'en',
    preferredClientId: 23139,
    locale: 'en',
    userId: 26087,
    loggedInUserClientId: 23139,
};

export const ModelDBResponse = [
    {
        CompetencyModelGUID: '8f6a0e3b-6b6d-4e5d-8f6a-0e3b6b6d4e5d',
        CompetencyModelVersion: '1.0',
        CompetencyModelName: 'CLM Test Company 1 Model',
        CompetencyModelDescription: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors',
        CompetencyModelParentType: 'KFLA',
        IsActive: 1,
        IsCustomCompetencyModel: 1,
        ClientID: 23139,
        LCID: 'en',
        LocaleName: 'English',
        MasterCompetencyModel: 1,
        CompetencyModelTemplateName: 'KFLA',
    },
];

export const ModelDataResponse = {
    models: [
        {
            id: '8f6a0e3b-6b6d-4e5d-8f6a-0e3b6b6d4e5d',
            version: '1.0',
            clientId: 23139,
            type: 'KFLA',
            parentType: 'KFLA',
            name: 'CLM Test Company 1 Model',
            description: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors',
            isActive: true,
            isCustom: true,
            outputType: 'RESPONSIBILITY',
            locales: [
                {
                    locale: 'en',
                    localeName: 'English',
                    isMaster: true,
                },
            ],
        },
    ],
};

export const NewModelDBResponseMock = [
    {
        CompetencyModelGUID: '20B4BA29-8050-48BD-8623-46FC14B7E165',
        CompetencyModelVersion: 1,
        ClientID: 23139,
        CompetencyModelTemplateName: 'KFLA',
        CompetencyModelParentType: 'KFLA',
        CompetencyModelName: 'CLM Test Company 1 Model',
        CompetencyModelDescription: 'CLM Test Company 1 Model',
        IsActive: 1,
        IsCustomCompetencyModel: 1,
        LCID: 'en',
        CompetencyModelCreatedOn: 'NULL',
        CompetencyModelModifiedOn: 'NULL',
        CompetencyModelCreatedBy: 'NULL',
        CompetencyModelModifiedBy: 'NULL',
        JobCategoryID: 99903,
        JobCategoryName:
            '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me',
        JobCategoryDescription: 'Custom JobSubFamily',
        JobSubCategoryID: 242963,
        JobSubCategoryName: 'Branch Operations',
        JobSubCategoryDescription: 'Design and/or deliver tasks to effectively operate a local office that provides face-to-face service to customers.',
        JobSubCategoryOrder: 50,
        IsCustomJobSubCategory: 0,
        DisplayJobSubCategory: 1,
        JobSubCategoryCreatedOn: '',
        JobSubCategoryModifiedOn: '',
        JobSubCategoryCreatedBy: 1234,
        JobSubCategoryModifiedBy: 26406,
        JobSubCategoryDependantID: 32424,
        JobSubCategoryDependantName: 'NULL',
        CoreSupportFlag: true,
        SkillsCount: 1,
        JobCategoryOrder: 145,
        IsCategoryEnabled: 1,
        DENSERANK: 1,
        RNK: 1,
    },
];

export const NewModelAPIResponse = {
    models: {
        id: '20B4BA29-8050-48BD-8623-46FC14B7E165',
        version: 1,
        clientId: 23139,
        type: 'KFLA',
        parentType: 'KFLA',
        name: 'CLM Test Company 1 Model',
        description: 'CLM Test Company 1 Model',
        isActive: true,
        isCustom: true,
        locale: 'en',
        categories: [
            {
                id: 99903,
                name: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me',
                description: 'Custom JobSubFamily',
                isCategoryEnabled: 1,
                subCategories: [
                    {
                        id: 242963,
                        name: 'Branch Operations',
                        order: 50,
                        isCustom: false,
                        isActive: true,
                        definition: 'Design and/or deliver tasks to effectively operate a local office that provides face-to-face service to customers.',
                        skillsCount: 1,
                        dependents: [
                            {
                                id: 32424,
                                name: 'NULL',
                                isCore: true,
                            },
                        ],
                    },
                ],
            },
        ],
    },
    status: 'MODIFIED',
};

export const ModelDetailAPIResponse = [
    {
        subCategories: [
            {
                id: 99903,
                name: '02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me',
                definition: 'Custom JobSubFamily',
                isCustom: true,
                isActive: true,
                originalName: '',
                originalDefinition: '',
                descriptions: [
                    {
                        id: 123,
                        level: 1,
                        description: 'Custom JobSubFamily',
                        originalDescription: '',
                        isCustom: true,
                    },
                ],
            },
        ],
    },
];

export const DefaultModelQuery = {
    locale: 'en',
    userId: 26087,
    loggedInUserClientId: 23139,
};

export const GetResponsibilityDetailIdDBResponseMock = [
    {
        JobSubCategoryId: 278551,
        JobSubCategoryName: 'ASHIM RESP HACKATHON test1',
        JobSubCategoryDescription: 'Test',
        DisplayJobSubCategory: 1,
        IsCustomJobSubCategory: 0,
        JobSubCategoryIsActive: 1,
        JobLevelDetailID: 3483751,
        JobLevelID: 12675,
        JobLevelDetailDescription: 'This level is not relevant for this responsibility',
        JobSubCategoryOriginalName: 'Economic Research',
        JobSubCategoryOriginalDescription:
            'Develop, carry out, or support a program of study designed to understand how limited resources, including land, labor, and/or capital are used by nations, organizations, households or individuals.',
        OriginalJobLevelDescription: 'This level is not relevant for this responsibility',
        IsCustomLevel: 0,
    },
    {
        JobSubCategoryId: 278551,
        JobSubCategoryName: 'ASHIM RESP HACKATHON test1',
        JobSubCategoryDescription: 'Test',
        DisplayJobSubCategory: 1,
        IsCustomJobSubCategory: 0,
        JobSubCategoryIsActive: 1,
        JobLevelDetailID: 3483757,
        JobLevelID: 12676,
        JobLevelDetailDescription: 'This level is not relevant for this responsibility',
        JobSubCategoryOriginalName: 'Economic Research',
        JobSubCategoryOriginalDescription:
            'Develop, carry out, or support a program of study designed to understand how limited resources, including land, labor, and/or capital are used by nations, organizations, households or individuals.',
        OriginalJobLevelDescription: 'This level is not relevant for this responsibility',
        IsCustomLevel: 0,
    },
];

export const GetResponsibilityDetailIdResponse = {
    subCategories: [
        {
            id: 278551,
            name: 'ASHIM RESP HACKATHON test1',
            isActive: true,
            isCustom: false,
            definition: 'Test',
            originalDefinition:
                'Develop, carry out, or support a program of study designed to understand how limited resources, including land, labor, and/or capital are used by nations, organizations, households or individuals.',
            originalName: 'Economic Research',
            descriptions: [
                {
                    id: 3483751,
                    level: 12675,
                    description: 'This level is not relevant for this responsibility',
                    originalDescription: 'This level is not relevant for this responsibility',
                    isCustom: false,
                },
                {
                    id: 3483757,
                    level: 12676,
                    description: 'This level is not relevant for this responsibility',
                    originalDescription: 'This level is not relevant for this responsibility',
                    isCustom: false,
                },
            ],
        },
    ],
};

export const responsibiltiesRepositoryResponse = {
    descriptions: [
        {
            description: 'Test',
            isCustom: true,
            level: 1,
            levelLabel: 'Test',
            name: 'Test',
        },
    ],
};

export const addNewSubcategoriesBody: AddNewSubcategories.Body = {
    categories: [
        {
            id: 99903,
            subCategories: [
                {
                    en: {
                        name: 'im02',
                        description: 'endescription',
                        levels: [
                            {
                                description: 'enlevel1',
                                isCustom: true,
                                level: 1,
                            },
                            {
                                description: 'enlevel2',
                                isCustom: true,
                                level: 2,
                            },
                            {
                                description: 'enlevel3',
                                isCustom: true,
                                level: 3,
                            },
                            {
                                description: 'enlevel4',
                                isCustom: true,
                                level: 4,
                            },
                        ],
                    },
                    de: {
                        name: 'im02',
                        levels: [
                            {
                                description: 'deLevel1',
                                isCustom: true,
                                level: 1,
                            },
                            {
                                description: 'deLevel2',
                                isCustom: true,
                                level: 2,
                            },
                            {
                                description: 'deLevel3',
                                isCustom: true,
                                level: 3,
                            },
                            {
                                description: 'deLevel4',
                                isCustom: true,
                                level: 4,
                            },
                        ],
                        description: 'sw',
                    },
                },
            ],
        },
    ],
    subFamilyId: 'S1032110001',
};
export const status: [{ Modification: string }] = [
    {
        "Modification": "PUBLISHED"
    }
];

export const NewModelResponsibilitiesDBResponseMock: NewModelDBResponse[] = [
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 242525,
        "JobSubCategoryName": "Spell-Checker Tools",
        "JobSubCategoryDescription": "Ability to identify and use appropriate spell-check tools.",
        "JobSubCategoryOrder": 503,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 1,
        "JobSubCategoryCreatedOn": "2021-01-08T19:56:31.94",
        "JobSubCategoryModifiedOn": "2024-02-29T13:12:36.187",
        "JobSubCategoryCreatedBy": null,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": 16050458,
        "JobSubCategoryDependantName": "Hand held spell checkers",
        "CoreSupportFlag": false,
        "SkillsCount": 4,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1623,
        "RNK": 1
    },
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 242525,
        "JobSubCategoryName": "Spell-Checker Tools",
        "JobSubCategoryDescription": "Ability to identify and use appropriate spell-check tools.",
        "JobSubCategoryOrder": 503,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 1,
        "JobSubCategoryCreatedOn": "2021-01-08T19:56:31.94",
        "JobSubCategoryModifiedOn": "2024-02-29T13:12:36.187",
        "JobSubCategoryCreatedBy": null,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": 16050459,
        "JobSubCategoryDependantName": "Spellex AccuCount",
        "CoreSupportFlag": false,
        "SkillsCount": 4,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1624,
        "RNK": 2
    },
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 242525,
        "JobSubCategoryName": "Spell-Checker Tools",
        "JobSubCategoryDescription": "Ability to identify and use appropriate spell-check tools.",
        "JobSubCategoryOrder": 503,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 1,
        "JobSubCategoryCreatedOn": "2021-01-08T19:56:31.94",
        "JobSubCategoryModifiedOn": "2024-02-29T13:12:36.187",
        "JobSubCategoryCreatedBy": null,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": 16050460,
        "JobSubCategoryDependantName": "Spelling and grammar checking software",
        "CoreSupportFlag": false,
        "SkillsCount": 4,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1625,
        "RNK": 3
    },
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 242525,
        "JobSubCategoryName": "Spell-Checker Tools",
        "JobSubCategoryDescription": "Ability to identify and use appropriate spell-check tools.",
        "JobSubCategoryOrder": 503,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 1,
        "JobSubCategoryCreatedOn": "2021-01-08T19:56:31.94",
        "JobSubCategoryModifiedOn": "2024-02-29T13:12:36.187",
        "JobSubCategoryCreatedBy": null,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": 16050461,
        "JobSubCategoryDependantName": "Sylvan Software Complete Medical Pharmaceutical Spell Checker",
        "CoreSupportFlag": false,
        "SkillsCount": 4,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1626,
        "RNK": 4
    },
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 242526,
        "JobSubCategoryName": "Language Reference Tools",
        "JobSubCategoryDescription": "Ability to identify and use appropriate language reference tools, such as dictionaries and thesauruses, both digital and print.",
        "JobSubCategoryOrder": 507,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 1,
        "JobSubCategoryCreatedOn": "2021-01-08T19:56:31.94",
        "JobSubCategoryModifiedOn": "2024-02-29T11:02:01.417",
        "JobSubCategoryCreatedBy": null,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": 16050462,
        "JobSubCategoryDependantName": "American Sign Language ASL browser",
        "CoreSupportFlag": false,
        "SkillsCount": 3,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1627,
        "RNK": 1
    },
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 242526,
        "JobSubCategoryName": "Language Reference Tools",
        "JobSubCategoryDescription": "Ability to identify and use appropriate language reference tools, such as dictionaries and thesauruses, both digital and print.",
        "JobSubCategoryOrder": 507,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 1,
        "JobSubCategoryCreatedOn": "2021-01-08T19:56:31.94",
        "JobSubCategoryModifiedOn": "2024-02-29T11:02:01.417",
        "JobSubCategoryCreatedBy": null,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": 16050463,
        "JobSubCategoryDependantName": "Electronic dictionaries",
        "CoreSupportFlag": false,
        "SkillsCount": 3,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1628,
        "RNK": 2
    },
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 242526,
        "JobSubCategoryName": "Language Reference Tools",
        "JobSubCategoryDescription": "Ability to identify and use appropriate language reference tools, such as dictionaries and thesauruses, both digital and print.",
        "JobSubCategoryOrder": 507,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 1,
        "JobSubCategoryCreatedOn": "2021-01-08T19:56:31.94",
        "JobSubCategoryModifiedOn": "2024-02-29T11:02:01.417",
        "JobSubCategoryCreatedBy": null,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": 16050464,
        "JobSubCategoryDependantName": "University of California Thesaurus Linguae Graecae TLG",
        "CoreSupportFlag": false,
        "SkillsCount": 3,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1629,
        "RNK": 3
    },
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 306249,
        "JobSubCategoryName": "Flight Plan Management",
        "JobSubCategoryDescription": "Ability to create efficient and safe flight plans.",
        "JobSubCategoryOrder": 217,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 0,
        "JobSubCategoryCreatedOn": "2021-07-02T13:03:30.927",
        "JobSubCategoryModifiedOn": "2024-02-29T16:54:11.307",
        "JobSubCategoryCreatedBy": 0,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": null,
        "JobSubCategoryDependantName": null,
        "CoreSupportFlag": null,
        "SkillsCount": 1,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1,
        "RNK": 1
    },
    {
        "CompetencyModelGUID": "20b4ba29-8050-48bd-8623-46fc14b7e165",
        "CompetencyModelVersion": 1.0,
        "ClientID": 23139,
        "CompetencyModelTemplateName": "KFLA",
        "CompetencyModelParentType": "KFLA",
        "CompetencyModelName": "CLM Test Company 1 Model",
        "CompetencyModelDescription": "CLM Test Company 1 Model",
        "IsActive": 1,
        "IsCustomCompetencyModel": 1,
        "LCID": "en",
        "CompetencyModelCreatedOn": null,
        "CompetencyModelModifiedOn": null,
        "CompetencyModelCreatedBy": null,
        "CompetencyModelModifiedBy": null,
        "JobCategoryID": 94287,
        "JobCategoryName": "02.17.2021 smoke CL added function 111 2 4Construction Project Delivery Behavioral competencies are observable behaviors | 02.17.2021 smoke CL added subfunction edited by me",
        "JobCategoryDescription": "Custom JobSubFamily",
        "JobSubCategoryID": 306258,
        "JobSubCategoryName": "Flight Spatial Awareness",
        "JobSubCategoryDescription": "Ability to detect the position of the aircraft/other aircraft both when in the air and taxiing on the ground, particularly in dark or cloudy conditions.",
        "JobSubCategoryOrder": 219,
        "IsCustomJobSubCategory": 0,
        "DisplayJobSubCategory": 1,
        "JobSubCategoryCreatedOn": "2021-07-02T13:03:30.927",
        "JobSubCategoryModifiedOn": "2024-02-29T14:14:26.197",
        "JobSubCategoryCreatedBy": 0,
        "JobSubCategoryModifiedBy": 26406,
        "JobSubCategoryDependantID": null,
        "JobSubCategoryDependantName": null,
        "CoreSupportFlag": null,
        "SkillsCount": 1,
        "JobCategoryOrder": 87,
        "IsCategoryEnabled": 1,
        "DENSERANK": 1,
        "RNK": 1
    },
];