environmentVariables:
  USE_JSON_LOGGER:
    secret: false
    value: '"False"'
  DEBUG:
    secret: false
    value: '"False"'
  AWS_SECRET_NAME:
    secret: false
    value: '/system/platform/postgres/profile-manager-secret-001'
  AWS_REGION:
    secret: false
    value: 'us-east-1'
  Environment:
    secret: false
    value: 'dev'
  REMOTE_LOADER_COMMONCONFIG_URL:
    value: 'http://localhost:2772/applications/kfone-dev-use1-appconfig-app-001-common/environments/dev/configurations/Common-Config'
  REMOTE_LOADER_LOGCONFIG_URL:
    value: 'http://localhost:2772/applications/kfone-dev-use1-appconfig-app-001-common/environments/dev/configurations/Logging'
  CONFIG_URL:
    value: 'http://localhost:2772/applications/kfone-dev-use1-appconfig-app-001-profile-manager/environments/dev/configurations/profile-manager-config'
  NODE_TLS_REJECT_UNAUTHORIZED:
    value: '"0"'
credentialsRequest:
  secret_resource_arn:
    - 'arn:aws:secretsmanager:us-east-1:011528287407:secret:/system/platform/postgres/profile-manager-secret-001-ItWwDQ'
